### ISSUE TITLE
Add "UNSCHEDULED" value for StopTimeUpdate.ScheduleRelationship for frequency exact_times=0 trips

### ISSUE THREAD

**Issue by barbeau** [google/transit#102]
Currently, [TripDescriptor.ScheduleRelationship](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-schedulerelationship-1) has an enum value of `UNSCHEDULED`, which is defined as:

>A trip that is running with no schedule associated to it - this value is used to identify trips defined in GTFS frequencies.txt with exact_times = 0. It should not be used to describe trips not defined in GTFS frequencies.txt, or trips in GTFS frequencies.txt with exact_times = 1.

However, it's not clear what cooresponding enum value should be used for exact_times=0 trips for [StopTimeUpdate.ScheduleRelationship](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-schedulerelationship), as it doesn't have an `UNSCHEDULED` value.

As a result, you could potentially have a feed that looks like this, which is not clearly labeled as incorrect in the current spec:

~~~
entity {
  id: "1121"
  trip_update {
    trip {
      trip_id: "5"
      start_time: "19:29:28"
      start_date: "20180910"
      schedule_relationship: UNSCHEDULED
      route_id: "C"
    }
    stop_time_update {
      stop_sequence: 1
      arrival {
        time: 1536609516
      }
      stop_id: "421"
      schedule_relationship: SCHEDULED
    }
    stop_time_update {
      stop_sequence: 2
      arrival {
        time: 1536609552
      }
      stop_id: "425"
      schedule_relationship: SCHEDULED
    }
~~~

Furthermore, because `SCHEDULED` is the default value if `schedule_relationship` is left empty, we need a separate enum value to represent exact_times=0 trips.

Therefore, I believe an `UNSCHEDULED` enum value should be added to StopTimeUpdate.ScheduleRelationship to fix this, with a definition of:

>The vehicle is proceeding in accordance with the order of stops defined in GTFS stop_times.txt for a trip with frequencies.txt exact_times = 0 or empty. It should not be used to describe a stop on a trip not defined in GTFS frequencies.txt, or for a stop on a trip in GTFS frequencies.txt with exact_times = 1.

**Comment by skinkie** [comment]
What was the value that we removed last time here?

**Comment by barbeau** [comment]
@skinkie I think [this removal](https://groups.google.com/forum/#!topic/gtfs-realtime/77c3WZrGBnI) of the `REPLACEMENT` value for `TripDescriptor.ScheduleRelationship` is most likely the removal you're thinking of.  This proposal isn't related, as it's for `StopTimeUpdate.ScheduleRelationship`, not `TripDescriptor.ScheduleRelationship`.

**Comment by paulswartz** [comment]
If the TripDescriptor.ScheduleRelationship is already UNSCHEDULED (meaning that the trip is running with exact_times=0), can't clients infer that the StopTimeUpdate.ScheduleRelationship is also unscheduled? An ADDED TripDescription.ScheduleRelationship doesn't also have an equivalent value in the StopTimeUpdate.ScheduleRelationship, for example.

**Comment by barbeau** [comment]
@paulswartz We could write rules into the GTFS-rt spec language instructing consumers to infer this, but the data itself would still be conflicting (some protobuf consumer bindings automatically populate the data with the default values, so to software it looks like all the StopTimeUpdate.ScheduleRelationships are all populated as SCHEDULED, even if left empty in the feed).  For data quality, IMHO it's better to provide an explicit enum to make it all match up.

As regards to ADDED, IMHO ADDED is currently too under-specified as-is and barely useable - we plan to clean this up in Service Changes. So I wouldn't use that as an example to follow here.
