### ISSUE TITLE
Express trains passing through stations

### ISSUE THREAD

**Issue by archerian** [google/transit#116]
We have a system that doesn't provide accurate GPS co-ordinates of the train, but a requirement to show at a station B between A and C that the train coming in platform X isn't actually going to stop at the platform but pass through. Is there some means by which this can be sent as a realtime update? One option we were thinking of is if VehicleStopStatus could have an additional parameter PASSING_THROUGH to indicate the train is in between station A and B but only going to stop next at C. Once it crosses B then VehicleStopStatus becomes IN_TRANSIT_TO station C. Or it there an existing way to do this?

**Comment by barbeau** [comment]
@archerian To my knowledge there isn't a way to both indicate that a vehicle is before stop B but will skip stop B and go straight to stop C in a VehiclePosition feed.  You could just have `VehicleStopStatus` with `IN_TRANSIT_TO` station C, but then you're missing the information that the vehicle is actually currently between A and B.  

Do you have a strong requirement to include this info directly in the VehiclePositions feed?

As of today, in GTFS-realtime you can use a TripUpdate stop_time_update with `schedule_relationship: SKIPPED`, or an Alert with an Effect of `NO_SERVICE` for that stop_id and trip_id.

For example, the TripUpdate:

~~~
trip_update {
    trip {
      trip_id: "1234"
    }
    stop_time_update {
      stop_sequence: 1
      arrival {
        time: 1539037800
      }
      departure {
        time: 1539037800
      }
      stop_id: "A"
    }
    stop_time_update {
      stop_sequence: 2
      arrival {
        time: 1539037906
      }
      departure {
        time: 1539037906
      }
      stop_id: "B"
      schedule_relationship: SKIPPED
    }
    stop_time_update {
      stop_sequence: 3
      arrival {
        time: 1539038040
      }
      departure {
        time: 1539038040
      }
      stop_id: "C"
    }
~~~

Alert would look like:

~~~
    informed_entity {
      stop_id: "B"
      trip_id: "1234"
    }
    effect: NO_SERVICE
~~~

Note that we've also drafted a GTFS-ServiceChanges spec which would handle this case by modifying the trip itself:
http://bit.ly/gtfs-service-changes

This is currently in draft format but if you think it would meet your needs please let us know.

**Comment by jxeeno** [comment]
This is how I would approach it:

The current best practice for modelling timing points / non-revenue stops is to list them as being `drop_off_type`/`pickup_type` = 1 (as per http://gtfs.org/best-practices/#stop_times_2).  This would be the case for express trains passing through stations as well.

Since consumers should always be matching the real-time data back to the scheduled GTFS data, they should interpret `INCOMING_AT` to a stop that's listed as non-revenue in the schedule as being a train about to pass through a station.

Thoughts?

**Comment by abyrd** [comment]
@jxeeno that seems to me like a good way to model it.

**Comment by barbeau** [comment]
@jxeeno I agree that is the best way to handle it if the train never stops at B. My impression in the initial post was that the train *sometimes* bypassed B based on realtime decisions and there was a need to handle this in GTFS-realtime, but if not then the approach your cite is definitely preferred.

**Comment by archerian** [comment]
Thanks for all your ideas, the express trains are known to skip stations in advance. @barbeau also brought out a solution for impromptu skips which I know we will soon have to handle, so I'd say this thread is two birds with one stone!
