### ISSUE TITLE
Spanish translation falls behind English original

### ISSUE THREAD

**Issue by egorich239** [google/transit#13]
1. gtfs-realtime.proto in Spanish and probably README.md should include disclaimer that the Spanish version is for information only, and English version takes precedence in case of differences.
2. ScheduleRelationship::REPLACEMENT should be deleted from Spanish version of gtfs-realtime.proto
3. EntitySelector fields should get some descriptions in reference.md.

**Comment by egorich239** [comment]
(2) has been addressed by https://github.com/google/transit/pull/12

I can however spot other differences in the text. For example, start_time for frequency-based trips is required to be GTFS_start_time + N * headway.

**Comment by gcamp** [comment]
I would reopen this, the Spanish hasn't been updated for 7 years

**Comment by skinkie** [comment]
I guess some ChatGPT would save the day.

**Comment by isabelle-dr** [comment]
We have translations at https://github.com/MobilityData/gtfs.org that render the Spanish version of gtfs.org.
They are also out of date currently (not 7 years though), but we plan to translate the whole site in June. 

I think we can delete the Spanish documentation from here. 
cc @Sergiodero

**Comment by isabelle-dr** [comment]
[The PR is open](https://github.com/google/transit/pull/446) to removing Spanish translations from the google/transit repo, in favor of the more up-to-date translations that live on https://github.com/MobilityData/gtfs.org
