### ISSUE TITLE
Should tools really be part of this repository?

### ISSUE THREAD

**Issue by gcamp** [google/transit#157]
I see recently there's more movement in scripts part of this repository (which was empty before AFAIK), I'm trying to understand why it should be part of the same repository as specs. 

Scripts seems to have a different review process than spec changes (is that specified somewhere?). Is that different for Google employee and non-Google employee? It should probably be specified in https://github.com/google/transit/blob/master/gtfs/CHANGES.md

It makes following this repo harder on Github, because now not all PRs and issues are relevant to specs (which I think most people following this repo are interested in). 

If this is also a place where scripts should go, what is https://github.com/google/transitfeed role? It also includes scripts in addition to the library itself. 

Ping @aababilov

**Comment by barbeau** [comment]
I agree that https://github.com/google/transitfeed is a better home for tools (which include scripts).  https://github.com/google/transitfeed already hosts the "official" GTFS validator, schedule viewer, and other various tools.

**Comment by LeoFrachet** [comment]
Yup, I agree.

**Comment by barbeau** [comment]
@aababilov Any objections to moving the pathways visualization and translations scripts to https://github.com/google/transitfeed?

**Comment by aababilov** [comment]
This is a very fair point. I will move the scripts to transitfeed. Thanks a lot for the suggestion.

**Comment by aababilov** [comment]
Done.

https://github.com/google/transit/pull/158
https://github.com/google/transitfeed/pull/471

**Comment by barbeau** [comment]
Thanks @aababilov!

**Comment by aababilov** [comment]
My pleasure, @barbeau!

**Comment by barbeau** [comment]
@aababilov I see that `upgrade_translations.py` survived the transfer, but contains only a comment that it's moved:
https://github.com/google/transit/blob/master/gtfs/scripts/upgrade_translations.py

Could we remove the https://github.com/google/transit/tree/master/gtfs/scripts directory entirely so that others don't accidentally drop more tools into this directory?

**Comment by gcamp** [comment]
Readme should also be updated to not mention tools : https://github.com/google/transit/blob/master/README.md

**Comment by barbeau** [comment]
Fix in https://github.com/google/transit/pull/161 and https://github.com/google/transit/pull/160.  Thanks @aababilov!
