### ISSUE TITLE
Can we fix the version of the spec on developers.google.com?

### ISSUE THREAD

**Issue by aickin** [google/transit#181]
[Apologies for posting this here; I know this is the spec repo and not Google's webmaster. However, I could not find any way to get feedback to Google. I tried to post to the transitfeed, gtfs-changes, and transit-developers mailing lists; they were all either completely hidden or bounced my message as an outsider.]

I've been working on some GTFS tools, and I noticed a confusing mistake in the GTFS reference on developers.google.com (`parent_station` is not defined for boarding areas, though from the example feeds it was clearly intended to be used for boarding areas). I tracked down how to submit changes to the spec on this repo, only to find that the spec here has already been updated to correctly define `parent_station` for boarding areas.

Reference spec on developers.google.com: https://developers.google.com/transit/gtfs/reference/
Reference spec here on GitHub: https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md

Does anyone know who updates developers.google.com, and if we can ask them to do so with the newest version of the spec from this repo? I spent the better part of an hour puzzling over the inconsistency, and I don't want others to go through the same thing.

Thanks so much for all the great work you do!

**Comment by barbeau** [comment]
@aickin Thanks for the feedback, I'll pass this along to Google.

In the mean-time, you may want to check out https://gtfs.org/. It is sync'd directly to this repo, so it's always up-to-date.

**Comment by aickin** [comment]
Sounds good, and thanks for the info on gtfs.org. Feel free to close this issue out, as I 100% recognize this repo is not responsible for developers.google.com. (Or, alternately, feel free to leave it open to track the issue!).

**Comment by aababilov** [comment]
Hello from Google!
Thanks for the signal. I updated the documentation. Check it out at  https://developers.google.com/transit/gtfs/reference/
