### ISSUE TITLE
Change the definition of location_type=1

### ISSUE THREAD

**Issue by skinkie** [google/transit#182]
location_type=1 is currently defined as:
```Station. A physical structure or area that contains one or more platform.```

Given that for anything like an entrance or generic node for an on street bus stop a parent_station would be required. I could argue that the wording of location_type=1 should be more generic. I would suggestion something like:

```
Group. A logical entity that contains multiple stops, entrances/exits, boarding areas or generic nodes.
```

Lets have a discussion with Noun should be used.

**Comment by skinkie** [comment]
![bla](https://user-images.githubusercontent.com/502394/62952806-a59d6d00-bdec-11e9-86a0-2d94479b5ac0.png)
...please ignore the 6(!) different data points, for two stops, my eyes hurt as well.

But I would like to know if these two stops form a station, so I could maybe have a single icon on the middle of the road at a higher zoom level. Draw a pathway between north and south stop using the pedestrian crossing.

I am taking the example as simple as possible. Because I would like to know if this should or must not be grouped.

**Comment by abyrd** [comment]
@gcamp in my experience it is very common to have multiple separate physical stops with the same name, logically considered to be one "stop group", but not united under one building or physically separate structure. My understanding of the question at hand is the following: in many places it's standard practice to group most or all stops into this kind of groups. A large number (perhaps all) stops are defined to be part of a cluster with the same name. It is a requirement or existing practice to reflect those logical stop groupings in transit data sets.

Should GTFS reflect these logical groupings in its own way (with stations, or some new location_type)? Or should logical groupings be discarded, and only physical stop groupings (station buildings) be retained?

**Comment by paulswartz** [comment]
Our (@mbta) current GTFS combines these into a single parent station, but we received feedback from Google that this was invalid according to the spec. To that end, we are planning to replace some of these children with recommended transfers: https://groups.google.com/forum/#!topic/massdotdevelopers/ncwdhif6DaI

I think keeping them as children is likely what riders expect, so we'd be in favor of a change like this.

**Comment by skinkie** [comment]
Could Google comment how an entrance for these things could then be modeled? Should there be two additional parents stations, one for each stop on both sides?

**Comment by LeoFrachet** [comment]
I agree with @paulswartz, I've heard in the past Google insisting on this definition limiting station to physical structure. @dbabramov or @aababilov, could you give us your opinion on this possible change of definition?

@abyrd, you spoke about "cluster" of stops. A while ago (on 2018-11-09) I wrote an "Open Question" exactly on that in the GTFS-Pathways document:

> **Q4. Bus stops and stations [2018-11-09, LF]**
>
> Should close on-street bus stops be grouped as a station? IMHO it should not, since a station should be physical structure, either underground or as bus terminal. Also because this grouping could depend of the service, and two bus stops will be in the same “station” for regular bus, and at the same time subsequent stops of a local bus line.
>
> If agency want to group bus stops that they see logically connected, I would advocate to create a “cluster” concept, instead of extending the “station” concept to a blurry definition.
>
> => transfers.txt seems to be enough for now. 

If there is a need to represent such cluster (hearing @skinkie, there is), and if Google wants to keep `location_type=1` as they are, we could define `cluster` with a new location type, which could be parent either of stop (if they do not belong to a station) or of station.

**Comment by LeoFrachet** [comment]
Oh and also we have been working (Google & MobilityData) on a document describing how to model stop and station. We were planning to submit it to the community next month, but since it is exactly the conversation we are having in this thread, here it is: 

https://docs.google.com/document/d/1zQ2SEHh3Uvv3kkmOoeMCCSzyS5ny5_ZPQyS2gG0yVk0

**Comment by skinkie** [comment]
> If there is a need to represent such cluster (hearing @skinkie, there is), and if Google wants to keep `location_type=1` as they are, we could define `cluster` with a new location type, which could be parent either of stop (if they do not belong to a station) or of station.

Do you see now why I find it strange that a stop (on its own) can't be the parent_station of an entrance?

**Comment by antrim** [comment]
The current definition for `location_type = 1`:
> • 1: Station. A physical structure or area that contains one or more platform.

"Platform" suggests this applies for rail stations, rather than modes like buses or ferries. What about bays in a bus station or docks in a ferry terminal? I suggest we modify the spec to make this mode agnostic.

Example to consider -- RTC Washoe's [4th Street Station (Transitfeeds link)](https://transitfeeds.com/p/rtc-washoe/46/latest/stop/9999) in Reno, NV:

![image](https://user-images.githubusercontent.com/6495639/94743111-b29c5900-032b-11eb-8836-d837312665ce.png)
https://goo.gl/maps/82tpDgin7NvyzVKh6

**Comment by LeoFrachet** [comment]
+1 as long as the bays/platforms/quays are in a building or area under the control of the agency, aka it will be only closed on the decision of the agency, and not because the city is doing construction in the street.

**Comment by skinkie** [comment]
Keep open.

**Comment by derhuerst** [comment]
still relevant
