### ISSUE TITLE
Document that GTFS-realtime feeds/entities aren't ordered unless stated

### ISSUE THREAD

**Issue by barbeau** [google/transit#185]
From @abyrd in https://github.com/google/transit/pull/176#issuecomment-521537063:

>I would prefer a blanket statement that feeds are not ordered, higher up in the document hierarchy outside any particular topic like blocks of trips. Or if people find it confusing to say that the data structure is unordered (if they see files and streams as inherently ordered), then just a statement that the order does not have any meaning.

And my response:

>I agree that it would be useful to state somewhere at the top that entities aren't assumed to be ordered unless otherwise stated. However, I do think it's useful to call this out specifically for trip updates. The reason for the question here is that stop_time_updates ARE required to be ordered within a trip_update. Because trips have an order in a block in GTFS, it's reasonable to ask if the ordering of stop_time_updates in GTFS-realtime extends beyond the trip_update to the entire block (i.e., multiple trip_updates).
>
>Given the vote for this passed, I'll go ahead and merge and then work on another proposal for this.

**Comment by skinkie** [comment]
Keep open.
