### ISSUE TITLE
fare_rules.txt and a conditionally required agency_id

### ISSUE THREAD

**Issue by skinkie** [google/transit#187]
Google Transit seems to have received a private extension to have an agency_id added in fare_attributes.txt, in similar fashion how a conditionally required agency_id exists in routes.txt. I assume this is done in order to allow multiple agencies sharing the **same** route_id. But that does not make sense since trip_id does not have an agency_id either.

> A fare attribute was found in the fare_attributes.txt file without an agency_id value. In a feed with multiple agencies defined in the agency.txt file, each fare attribute must specify an agency_id value to indicate which agency the fare applies to.

**Comment by antrim** [comment]
I think that we should add `fare_attributes`.`agency_id` to add to the spec. Trillium currently supports this in order to specify fares in multi-agency feeds (e.g. https://transitfeeds.com/p/arcata-mad-river-transit-system/148/latest/file/fare_attributes.txt). I suspect this is broadly used, but am not sure.

**Comment by skinkie** [comment]
@antrim have you seen the discrepancy in my comment?

**Comment by antrim** [comment]
@skinkie : I didn't follow everything, particularly the part about "allow multiple agencies sharing the **same** route_id". I noticed that you're discussing both `fare_rules.txt` and and `fare_attributes.txt` but didn't parse everything out. Instead, I thought it was simpler to just share Trillium's practice. If there's more to explore or a correction/clarification to make, please share!

**Comment by skinkie** [comment]
In order to merge a feed the tripids of feed A and B must not have any value in common. The same would go for route_id. Hence you can't have a route_id and trip_id combination that is less unique than a agency_id, route_id and trip_id. I wonder if it therefore would make sense to have an agency_id, if agency_id is in fact an attribute and not a compound key.

**Comment by antrim** [comment]
Yup! I was thrown off by this:
> Google Transit seems to have received a private extension to have an agency_id added in fare_attributes.txt

`fare_attributes`.`agency_id` is already part of the spec.

I'd favor leaving `fare_rules.txt` as it is. Could we close this issue?

**Comment by skinkie** [comment]
Want to have a discussion on this topic...
