### ISSUE TITLE
GTFS-Ticketing (with deep links)

### ISSUE THREAD

**Issue by LeoFrachet** [google/transit#190]
In transportation apps, riders search for O to D trips, check the different options, and choose among them the one they want to take.

But once their decision is made, a ticket has to be bought to make the ride. A growing number of public transit agencies already have ticketing apps allowing the rider to pay for such a ticket, but currently, links between transportation apps and ticketing apps have to be ad-hoc.

The goal of this proposal is to standardize the deep links between transportation apps and ticketing apps or websites, allowing the rider to have the following smooth experience:
• Search for O to D in transportation app.
• Choose the option they want in the transportation app.
• Be redirected in the ticketing app to buy the ticket, without having to re-enter the information about the OD nor the choice they made.
• Buy the ticket (or book).

=> [bit.ly/gtfs-ticketing](http://bit.ly/gtfs-ticketing)

(Note: it used to be called GTFS-DeepLinks)

**Comment by skinkie** [comment]
What is the reason to make this proposal overly complex and not mandating that a provider is using the same ids for their stop, route, trip?

Why is the proposal not using something like a path template the agency can configure theirselves, opposed to the mandated url structure which is **never going to work**.

http://path.to.api/${from_stop_id}/${to_stop_id}

**Comment by dbabramov** [comment]
Hi, Stefan,

Thank you for your comment.

The reasons why Google would prefer to have a separate set of ids for stops and trips are the following:
1. Agencies already have ticketing mobile applications and websites that already have their ways of identifying trips and stops for ticketing. 
These websites/apps should not be modified when the agency decides to change the schema for their ids in GTFS. Even if the agency can update the website with the rollout of a new GTFS update, updates for mobile apps could lag behind updates and cause ticketing functionality within these apps to break at least temporarily.
2. Stop and route ids are not guaranteed to remain unchanged over time. Agencies may need to change stop/route ids from time to time, for example when adding platform information to a feed.
3. GTFS consumers (such as Google) in some cases receive feeds through third-party aggregators, whose software replaces ids within the feed. 

That is why we recommended that ids for ticketing purposes are provided in a separate column.
Please let me know if this answers your question.

Regards,
Dmitri.

**Comment by brycekahle** [comment]
Can you elaborate on the reason GTFS-DeepLinks was changed to be specific to ticketing? I have a use case where the ability to share OD information between apps would be very useful, without the need for ticketing information.

**Comment by skinkie** [comment]
> That is why we recommended that ids for ticketing purposes are provided in a separate column.
> Please let me know if this answers your question.

The identification part, but not the URL part. Especially because you wrote that the agency should not change their existing application. That would suggest a templating approach opposed to a standard URL.

**Comment by derhuerst** [comment]
> Can you elaborate on the reason GTFS-DeepLinks (now GTFS-Ticketing) is specific to ticketing? I have a use case where the ability to share OD information between apps would be very useful, without the need for ticketing information.

I'd like to make that point as well. **There are many use cases other than ticketing that require (and deserve!) proper URIs** for O to D trips, e.g. checking into a trip, storing it in a personal travel log, or sharing it with others.

I'm afraid though that, whatever scheme this proposal comes up with, it won't be flexible enough for nuanced real-world use cases. The tickets available might depend on e.g. a trip you took before (e.g. a local train after an express train). I see the URL template, as proposed by @skinkie, as a reasonable way to allow for that complexity, while still standardising the common parameters such as `from_stop_id` etc.

**Comment by skinkie** [comment]
Keep open.

**Comment by derhuerst** [comment]
still relevant

**Comment by skinkie** [comment]
It seems that Google has added deeplinks. https://developers.google.com/transit/gtfs/reference/google-transit-ticketing-extension?hl=en#examples
