### ISSUE TITLE
StopTime dependent bike allowance

### ISSUE THREAD

**Issue by hbruch** [google/transit#198]
Currently, GTFS supports bike_allowed as attribute for trips.

However, very often, bike allowance is either time-dependent (e.g. disallowed on workdays between 6am and 8:30am) or stop-dependent (e.g. boarding only allowed at first stop, unboarding only at the last).

I'd like to suggest to extend StopTimes.txt by two new attributes "bikePickupType" and "bikeDropoffType", with the following values:

For bikePickupType:
```
NO_BIKES_PICKUP_INFORMATION = 0
BIKES_PICKUP_ALLOWED = 1
NO_BIKES_PICKUP = 2 
```

For bikeDropoffType:
```
NO_BIKES_DROPOFF_INFORMATION = 0
BIKES_DROPOFF_POSSIBLE = 1
NO_BIKES_DROPOFF = 2
BIKES_DROPOFF_MANDATORY = 3
```

If this is a need felt by others as well, I'd prepare a PR to discuss this further. If there are already ongoing efforts I'm not aware of, please let me know.

**Comment by skinkie** [comment]
I would support this.

**Comment by paulswartz** [comment]
@mbta is also in favor.

**Comment by scmcca** [comment]
Any developments on turning this into a PR?
