### ISSUE TITLE
TripDescriptor hasScheduleRelationship incorrectly returns false

### ISSUE THREAD

**Issue by zachpepsin** [google/transit#201]
Today when working with the SEPTA GTFS-Rt feed, I found that the TripDescriptor hasScheduleRelationship() was returning false even for times when there were SCHEDULED schedule relationships present.  SEPTA does not have any other statuses in their feed besides SCHEDULED, so that is all I was able to test.  I'm unsure if this issue is present for other statuses.

**Comment by barbeau** [comment]
@zachpepsin Sounds like this is an issue with the gtfs-realtime-bindings library?  Could you please open an issue there instead - https://github.com/MobilityData/gtfs-realtime-bindings? Thanks!
