### ISSUE TITLE
Should TripUpdates be required to be ordered in feed by block-order?

### ISSUE THREAD

**Issue by barbeau** [google/transit#207]
This discussion thread was requested by @skinkie in https://github.com/google/transit/pull/206/files#r385850432.

https://github.com/google/transit/pull/176 documented the current practice in GTFS-realtime that TripUpdates do not have to be listed in block-order in the feed.

For example, if there are trips with `trip_ids` 1, 2, and 3 that all belong to one block, and the vehicle travels trip 1, then trip 2, and then trip 3, the `trip_update` entities may appear in any order - for example, adding trip 2, then trip 1, and then trip 3 is allowed.

The spec [does say](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/trip-updates.md#stop-time-updates) that within a trip, `stop_time_updates` must be provided in stop sequence-order.

Could some producers and consumers please weigh in on their opinions if we should require TripUpdate entities be ordered by block-order within a feed?

@abyrd I know you had expressed some concerns about this previously (see https://github.com/google/transit/pull/176#issuecomment-516377849).

**Comment by paulswartz** [comment]
If anything, I'd prefer sorting them by time, rather than specifically by block. But I think clients sorting by time would also have them sorted by block, so might be a moot point.

**Comment by barbeau** [comment]
@paulswartz By departure time of first stop_time_update in trip_update?

**Comment by paulswartz** [comment]
That seems like a good interpretation to me!
