### ISSUE TITLE
How are you using Alerts with effect of ACCESSIBILITY_ISSUE?

### ISSUE THREAD

**Issue by barbeau** [google/transit#209]
Hi all! A question came up regarding the use of alerts labeled with the effect `ACCESSIBILITY_ISSUE`, which was adopted in PR https://github.com/google/transit/pull/164.

In [service-alerts.md](https://github.com/TransitApp/transit/blob/master/gtfs-realtime/spec/en/service-alerts.md#effect), it is defined as:

>Accessibility issue: The alert provides information about accessibility issues that affects step-free access. Examples include an out of service elevator or movable ramps.

Producers - What types of alerts are you labeling with `ACCESSIBILITY_ISSUE`?

(@paulswartz, @skinkie)

Consumers - How are you using `ACCESSIBILITY_ISSUE` alerts?

(@gcamp, @ibi-group-team)

Also cc'ing others from the original discussion in #164 (@harringtonp, @laurentg, @kurtraschke, @jrsanbornjr, @ritesh-warade-ibigroup, @jakluk)

**Comment by skinkie** [comment]
@barbeau at this moment we do not have any source data (yet) that labels an ACCESSIBILITY_ISSUE. Our first target is to use it in an automatic elevator status, hopefully closely related to the indoor navigation.

**Comment by gcamp** [comment]
We use that value internally to tag alerts as such. However, we have seen no agency use it yet.

**Comment by jakluk** [comment]
In Prague, we issue alert for a metro station when any of its lifts is not in operation. The customer should then confirm on the linked website whether an accessible path still exists or not. Previously we used effect OTHER (so that it is shown just as a low-priority information), now I changed it to ACCESSIBILITY_ISSUE and Google seems to have a hard time with it. No title is provided and highest severity icon is used. 
![accessibility_issue_alert](https://user-images.githubusercontent.com/1623193/87488563-00fd5e00-c641-11ea-9638-421c6889004f.png)

**Comment by laurentg** [comment]
Coming a bit late here, but looking at our alerts unfortunately none of them are of type ACCESSIBILITY_ISSUE, so we cannot tell.

However by looking at our database of 19796 alerts, we can share some anonymous statistics on the number per cause and effect, see below. It could be interesting for others to share their stats, our sample is a bit small. Google would have some better stats for sure ;)

```
 effect | count | effect
--------+-------+---------------
      3 |  8244 | SIGNIFICANT_DELAYS
      0 |  2266 | (UNSET)
      5 |  2204 | ADDITIONAL_SERVICE
      1 |  2177 | NO_SERVICE
      8 |  1542 | UNKNOWN_EFFECT
      6 |  1169 | MODIFIED_SERVICE
      7 |   987 | OTHER_EFFECT
      2 |   960 | REDUCED_SERVICE
     10 |    88 | NO_EFFECT
      4 |    84 | DETOUR
      9 |    75 | STOP_MOVED

 cause | count | cause
-------+-------+--------------
     9 |  6672 | MAINTENANCE
     1 |  5023 | UNKNOWN_CAUSE
     0 |  2116 | (UNSET)
     4 |  1805 | STRIKE
    10 |   980 | CONSTRUCTION
     5 |   887 | DEMONSTRATION
     8 |   820 | WEATHER
     2 |   734 | OTHER_CAUSE
     7 |   220 | HOLIDAY
     6 |   209 | ACCIDENT
    11 |   179 | POLICE_ACTIVITY
     3 |   151 | TECHNICAL_PROBLEM
    12 |     0 | MEDICAL_EMERGENCY
```

Oddly, in those times, the only cause that is never present in our dataset is 12 (MEDICAL_EMERGENCY)... Second oddity in my sense: the small number of alerts of cause 9 (STOP_MOVED).
