### ISSUE TITLE
How to express service suspensions during Covid-19?

### ISSUE THREAD

**Issue by antrim** [google/transit#224]
During Covid-19, many transit operators are suspending service for an extended period. Most transit services will come back, so it may do a disservice to customers if those routes can't be discovered online. How should service suspensions be represented in GTFS and GTFS-realtime? 

Please comment on proposed options.

- Option 1: Include routes and stop records, remove trips or cancel trips using calendar_dates.txt.
- Option 2: Include routes and stop records, cancel service using GTFS-realtime ServiceAlerts.
- Option 3: Should we consider a new field in `calendar.txt` that would indicate a suspended service?

The goal is to indicate to consuming applications the infrastructure and service still exists even when it's not operating. It will come back later.

Below is a table of a few services in the United States that have been suspended. Here is an example result in Google Maps for Sage Stage in Northern California: https://goo.gl/maps/mmKQRRpXYiS8Qw357

| Transit operator / agency | Service status |
|------------------------------|-----------------------|
| Airport Express (Sonoma, CA) | all service suspended |
| Arizona Shuttle              | all service suspended |
| Avalon Transit (CA)          | all service suspended |
| Basin (OR)                   | Quail Trail suspended |
| Beloit Transit               | all service suspended |
| Benton County Transit (OR)   | all service suspended |
| Bloom Bus                    | all service suspended |
| Blossom Express              | all service suspended |
| Bustang                      | all service suspended |
| Capital Transit (Helena)     | all service suspended |
| Cedar Rapids                 | all service suspended |
| Colorado Shuttle             | all service suspended |
| Columbia Area Transit (OR)   | all service suspended |
| Coos County (OR)             | one route suspended   |
| Coralville Transit System    | some routes suspended |
| Epic Mountain Express        | all service suspended |
| Green Ride                   | all service suspended |
| Groome Transporation         | all service suspended |
| Indian Trails                | all service suspended |
| Kayak (OR)                   | all service suspended |
| Laguna Beach Transit         | all service suspended |
| MuscaBus                     | all service suspended |
| MVRTD/The Bus (VT)           | one route suspended   |
| Oregon Express Shuttle       | all service suspended |
| Peter Pan                    | all service suspended |
| Plymouth & Brockton          | all service suspended |
| Sage Stage                   | all service suspended |
| Vail Transit                 | all service suspended |
| Washington Park Shuttle (OR) | all service suspended |
| Yankee Line (MA)             | all service suspended |

**Comment by skinkie** [comment]
This is a very good question especially regarding integration. If a system is based on the fact a file (or version) can define availability, then a new file should be presented. Option 1 makes the most sense to me. But the actual problem is: how to define that the service will start again in two weeks. Is a feed start date, with a later calendar date enough to define this. Because we don't have the option to inform the user of this thing with the "why" I would also include a message using GTFS-RT.

**Comment by stevenmwhite** [comment]
> Here is an example result in Google Maps for Sage Stage in Northern California: https://goo.gl/maps/mmKQRRpXYiS8Qw357

This example uses Option 2, correct?

I do like Option 2 for the fact that it still gives general information about the typical service (which you'd lose with option 1) and also gives information to riders about the current situation (in this case, customer contact numbers and social service info to help riders who may have used those trips to get groceries).

However, a problem with Option 2 is that is has the ability to bury trips that _are_ happening if consumers still display these canceled trips. Additionally, it appears that Google at least isn't displaying the alert for future trips (see this example of the same trip for Tuesday, which appears as if it will take place even though the alert lasts through 5/31: https://goo.gl/maps/8oheu7L5LpxTszA37 )

**Comment by gcamp** [comment]
If I'm only talking about Transit, we would prefer having alert with `NO_SERVICE`. In Transit we'll mark those services as no running without hiding them completely. The trip planner will also work around those services so you do get the best trip plan with current service. 

However I understand this would not be the best solution _currently_ for all consumers. Maybe it should be clarified in the spec the behaviour of `NO_SERVICE`. I know @barbeau had this in the plans at some point. 

I don't get how option 3 is useful, unless we really want to be able to define it statically. Alerts have the same capability and have on top useful description fields to explain what is happening to the user.

**Comment by paulswartz** [comment]
@mbta is doing 1 and 2. However, we haven't cancelled service for the entire duration of the GTFS feed, so no routes/trips are truncated out of the feed. 

This is something we don't have a great solution for in general, and it happens in some other cases as well:
- long-term stop closures
- long-term rail replacement bus shuttles

In both, there's a long-term change to the "normal" service and no great way to represent that in GTFS.
