### ISSUE TITLE
Moving a stop in GTFS-RT Service Change v3.1

### ISSUE THREAD

**Issue by john-burge-sys** [google/transit#226]
We are in the process of creating a GTFS-RT using the GTFS-RT Service Change v3.1. The need is to be able to incorporate information on detours and bus stop closures into our GTFS-RT feed. I understand that the change has not been approved by this group.

My scenario is simple. Close a stop and create an alternate stop on the next block from the exiting stop. Per the specification the original trip must be canceled and a new trip created with the new stop. It is the same sequence number as the original stop.  End result is that every trip that used the closed stop must be canceled and replaced with a new trip using the new stop.

For a stop that supports two routes with about 80 trips each/day and the stop will be closed for a week, the feed must publish 1120 new trips plus 1120 canceled trips for the next week. The stop times for the new trips remain unchanged from the original trips. Plus the new trips are trips with new trip_id's.

Our system does not create new trip numbers for internal or external systems except is a few situations like over load service. This helps to keep systems synchronized since all are using the original schedule trip id without having to have further information about the change. The biggest systems are faring, onboard information signs and stop displays.

My questions are:

1. Is there ever a need to keep the trip_id synchronized with the original trip_id via GTFS-RT?
2. Is there another option for a simple stop change so there would not need to be many cancelations and new trip creations?
3. Recommended updates are 1 to 10 times per hour. Is this a recommendation or what is expected for the number of updates a consumer should expect?

**Comment by Bertware** [comment]
Hi John,

There is an ongoing discussion about platform changes, but there are suggestions in the comments to allow changing the stop to an entirely different stop. It might be interesting for your case. https://github.com/google/transit/pull/219

Regards,
Bert

**Comment by barbeau** [comment]
@john-burge-sys Great to hear you're working on this!

>Is there ever a need to keep the trip_id synchronized with the original trip_id via GTFS-RT?

It would be great to get consumers like @tleboulenge (Google) and @gcamp (Transit App) to weigh in on this.

>Is there another option for a simple stop change so there would not need to be many cancelations and new trip creations?

Not currently, but as @Bertware mentioned there is a related discussion in #219 for platform changes that you may want to follow/contribute to. ServiceChanges v3.1 is still a draft spec so changes are still possible - feel free to comment directly in the Google Doc too - https://bit.ly/gtfs-service-changes-v3_1.

>Recommended updates are 1 to 10 times per hour. Is this a recommendation or what is expected for the number of updates a consumer should expect?

The SLOs defined in ServiceChanges v3.1 are more to help set expectations for discussions surrounding the draft spec based on conversations with producers and consumers - I wouldn't really call them "recommendations". The goal was to avoid misunderstandings  - for example, where producers were frequently publishing huge datasets that consumers weren't able to ingest that quickly.

Right now the SLO for new `Trips` says:

>* Frequency of update of the data is expected to be a few times per hour (1-10/hour).
>* Ingesting time on the data consumer side is expected to be 1-2 hours.

What frequency of update in your feed would you expect?

**Comment by john-burge-sys** [comment]
Thank you both for responding. 

I will read through #219 and comment there and in the document for the stop relocation items.

> What frequency of update in your feed would you expect?

What I am trying to understand is how to publish the new trip information. In our current implementation we have a feed where all of information is presented in a single .pb file. We also provide 3 feeds to provide specific data. 1 for Alerts, 1 for Vehicles and 1 for Trip Updates. And currently they are all updated every 30 seconds or less based on the need of the agency.

Service changes do not happen that often in normal operations that I am not worried about how frequently the information is updated. If the new trips are part of the single feed, the information would be updated every 30 seconds. But the information is not likely to change from the previously published feed. Should the new trip data be part of the single feed or does it make more sense to move the data to a separate feed?

I will also add comments to this topic in the google document also.

**Comment by barbeau** [comment]
> Should the new trip data be part of the single feed or does it make more sense to move the data to a separate feed?

@john-burge-sys This hasn't been defined in the ServiceChanges v3.1 spec, and we'd certainly welcome feedback based on early implementations. Certainly if there are the number of entities you refer to in the your initial post that aren't updated frequently, it would probably make sense to split that into a separate .pb file.

In the recent past there has been a push to get producers to consolidate entities into a single .pb file to avoid data inconsistency and sync issues between multiple .pb files. But that needs to be balanced with the size of the files and frequency of updates.

>Is there ever a need to keep the trip_id synchronized with the original trip_id via GTFS-RT?

You may have already seen this, but I also wanted to mention that there is a field `TripUpdate.replaced_by_trip_id` defined in the ServiceChanges spec that is intended to be an informational pointer between the original trip_id that was `CANCELED` and the new `Trip`(s) replacing it.

>`replaced_by_trip_id` - Defines which trip_id(s) (defined via GTFS-NewTrips) are replacing this trip. This is for information only and doesn’t cancel the original trip. If this field is populated, schedule_relationship for this trip should be CANCELED.
