### ISSUE TITLE
Exchanging predicted occupancy in GTFS

### ISSUE THREAD

**Issue by skinkie** [google/transit#233]
In GTFS-RT a transit agency can exchange occupancy information. I would like to pull the https://developers.google.com/transit/gtfs-realtime/reference#enum-occupancystatus into GTFS, specifically as column in stop_times.txt, to describe the predicted occupancy between the current stop to the next stop.

**Comment by devadvance** [comment]
Given the lengthy, pre-existing debate about the value of those specific enums (see #223), do you have more information on the type of occupancy you would wish to convey?

**Comment by skinkie** [comment]
I would like to send a prediction that enum beforehand. The discussion of what values the enum contains is irrevant. At this moment we have in use: no information (the null value), empty, many seats available, few seats available, standing room only, full.

**Comment by derhuerst** [comment]
> I would like to send a prediction with that enum beforehand. The discussion of what values the enum contains is irrevant.

But if GTFS-RT adopted the mentioned `OccupancyStatus` enum and #223 then came to the conclusion to remove/change it, we would have 2 (instead of 1) changes breaking existing implementations. Am I misunderstanding something here?

**Comment by skinkie** [comment]
In my opinion it should be the _same enum_. Regardless of the values that that enum at that moment in time contains. But if we are talking about a complete removal (where it changes to a percentage) this obviously should become the occupancy attribute that matches the occupancy attribute in GTFS-RT.

**Comment by skinkie** [comment]
Someone at mobility data is working on it, would be great if the discussion actually took place first.
#240
