### ISSUE TITLE
Tracking Canceled Trips that are Reinstated using GTFS-RT ServiceChange v3.1

### ISSUE THREAD

**Issue by john-burge-sys** [google/transit#243]
TransitMaster is implementing GTFS-RT ServiceChange v3.1. We are looking at the situation where a detour is created but later postponed. As part of the detour new trips are created to show the new path and stops. The detour is delayed so the initial modified trip is removed from the service change and when a vehicle is about to start on the trip, the original trip is included in trip update. Not the modified trip.

**Example**
Detour to start at 0900. Trip 12345 will run at 1000 and is replaced with new trip 12345-1. An Alert is created. Trip Update feed cancels trip 12345 and replacement trip 12345-1 is added. New trip is added to the service change feed along with the new shape and stops.

At 0830 there is a change to the detour to start at 1200. Alert feed is updated to reflect a new start time. Trip update will remove the canceled trip information for Trip 12345 and remove the new trip 12345-1 from the service change feed. Alert is modified to reflect the new start time. The new shape and stops are in the service change feed to support subsequent trips. When the trip starts the trip update feed with show the information for trip 12345.

**Question**
Is there a situation where the trip 12345-1 should be canceled in the trip update feed to support traceability that the trip was added to the Service Change feed and then removed?

**Comment by skinkie** [comment]
Out of curiosity. You are aware you are implementing a proposal that may (or may never) be actually standardised?

**Comment by john-burge-sys** [comment]
Thanks for the feedback. We will be implementing as suggested here.
