### ISSUE TITLE
Realtime reference and proto specifications do not match

### ISSUE THREAD

**Issue by muto-jo** [google/transit#256]
I found not match specification between gtfs-realtime reference and .proto file.

[In realtime reference]
message FeedHeader.icrementality is written at "Required".

https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md

| Field Name | Type | Required | Cardinality |
| -- | -- | -- | -- |
| incrementality | Incrementality | Required | One |

[In .proto]
message FeedHeader.icrementality is written at "optional".

https://github.com/google/transit/blob/master/gtfs-realtime/proto/gtfs-realtime.proto

```
optional Incrementality incrementality = 2 [default = FULL_DATASET];
```

I think .proto is correct.
I want to correct by anyone who known which correct.

**Comment by barbeau** [comment]
@muto-jo Good question! If you're asking the question "what fields do I need to provide for my feed to be valid GTFS-realtime", then you need to follow the requirements in the reference document. These are the semantic requirements of the spec. 

The definitions in the GTFS-realtime .proto field are the requirements of the protocol buffer encoding, which, based on [quirks of protocol buffers](https://developers.google.com/protocol-buffers/docs/proto#specifying_field_rules), means that all future fields will be marked as "optional" even if they are defined as required semantically (in the reference document). So there are and will be differences between these two documents.

See the top of the ["Required" section](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#required) in the reference documentation for details, including a link to the proposal that defined the semantic requirements for GTFS-realtime.
