### ISSUE TITLE
Articles 7.5 and 8 of the specification amendment process not being followed

### ISSUE THREAD

**Issue by scmcca** [google/transit#262]
Hi everyone,

We wanted to raise an issue around Article 7.5 and Article 8 of the [specification amendment process](https://github.com/google/transit/blob/master/gtfs-realtime/CHANGES.md#specification-amendment-process):
> If a vote was not called within 30 calendar days from the original proposal or 30 calendar days since end of the previous vote, then the proposal is abandoned.

> If the proposal is abandoned, the corresponding pull request is closed. Note that the advocate may choose to implement the feature as an custom extension instead of part of the official spec.

In current practice, PRs often remain open well after 30 days before a vote is called. The majority of open PRs have been so for months, if not years. What should we do about this?

There is merit in allowing PRs to be open for longer than 30 days as they get developed and deliberated on by the community. [google/transit](https://github.com/google/transit) is also an ideal venue to do so as it serves as the focal point of conversation and allows to preview how the proposal would actually look and read in the reference, putting it under more scrutiny to reach a final form or to be abandoned. Additionally, implementation by producers and consumers takes time. As proposals can get large or introduce major new features, it's ambitious to get everyone aligned and implemented on a proposal in 30 days or less. To do so on external branches may fragment the conversation.

I see a few options:
1. Enforce articles 7.5 and 8 as they are currently defined.
2. Extend the pre-vote period by more than 30 days (60, 90, etc). 
3. No time limit (removal of articles 7.5 and 8).
4. Define an allowance to renew the default 30-day pre-vote period if it is needed to continue a conversation.
5. Close or renew the PR after 30 calendar days since the last comment.

Options 4 and 5 could be leveraged to (i) clear the backlog of open PRs if they are not claimed, (ii) put the responsibility on the advocate to maintain discussions and keep the PR relevant, and (iii) can be called on a rolling basis per the developmental needs of the PR (i.e., instead of defining a strict period that applies for all PRs).

Looking forward to hearing some thoughts on this. Thanks!

**Comment by brodyFlannigan** [comment]
I personally think a combination of options 4 and 5 would be ideal.

**Comment by tsherlockcraig** [comment]
I support option 5. I don't have anything against option 4, but "post a comment" seems like a really easy process for renewing the 30 day period. (Only problematic loophole I can think of would be if someone set up a bot to post spam messages to keep a PR open, but frankly that'd be pretty funny.)

**Comment by e-lo** [comment]
I am in favor of option 5. 

I agree that it can take some time to implement on "both sides" but also support clearing out the backlog on stale PRs.
