### ISSUE TITLE
Agency icons

### ISSUE THREAD

**Issue by mpaine-act** [google/transit#269]
Would the GTFS standard please consider support for agency icon URLs with the agency.txt file?   It is useful when multi-modal data situations (e.g. trip planners) mix routes between different agencies, as agency's route colors are not always good enough to differentiate for accessibility purposes.

**Comment by skinkie** [comment]
I think we had this discussion before. I guess the main problem is that a _single_ icon is not what we want, so an icon pack could be an idea.

**Comment by barbeau** [comment]
See https://github.com/google/transit/pull/76 for previous discussion

**Comment by stevenmwhite** [comment]
Should we consolidate discussion here or over there?

I think generally there's an agency "logo" that represents the agency, but it may not be the icon/symbol that represents their services. One agency may have multiple services with distinct brands (circulators vs commuter routes, or rapid vs local) so perhaps the service icons should be defined at the route level? Both are important, and the route-level icons could be treated as an override to the agency-level one?

(I realized I asked where to discuss and then went ahead and wrote my comments here anyway... sorry)

**Comment by Cristhian-HA** [comment]
I will suggest to move this conversation to https://github.com/google/transit/pull/76 and close this one as there are already a bunch of suggestions and conversations on going regarding this subject.

**Comment by mpaine-act** [comment]
> Should we consolidate discussion here or over there?
> 
> I think generally there's an agency "logo" that represents the agency, but it may not be the icon/symbol that represents their services. One agency may have multiple services with distinct brands (circulators vs commuter routes, or rapid vs local) so perhaps the service icons should be defined at the route level? Both are important, and the route-level icons could be treated as an override to the agency-level one?
> 
> (I realized I asked where to discuss and then went ahead and wrote my comments here anyway... sorry)

This is what I had in mind.  At minimum, an agency icon can be used when route-level or stop-level icons are not defined.
