### ISSUE TITLE
GTFS-Performance: Exchanging historical transit performance data

### ISSUE THREAD

**Issue by ericouyang** [google/transit#280]
Hi GTFS community! 👋 

I'm working on a new standard to streamline the exchange of historical transit performance data, such as observed arrival/departure times, key performance indicators (KPIs) like on-time performance, and travel times, between systems and now are seeking broader feedback.

You can find the proposal at [bit.ly/gtfs-performance](http://bit.ly/gtfs-performance). Below, I've included an excerpt of the document and some prompts to help frame and guide the discussion.

Can't wait to hear what folks think! 

## Problem

Static GTFS enables producers to specify the network configuration and what is expected to happen, however, the sharing of what actually happened is not currently standardized, leading to fragmentation of both the production and analyses of historical transit data.

Extracting data from existing systems, such as a CAD/AVL (Computer Aided Dispatch/Automatic Vehicle Location), may be cumbersome, require technical knowledge, or simply not available. When data is retrieved from multiple systems, such as a separate Automatic Passenger Counter (APC) system, it may only have a partial picture, such as the boardings and alightings at a particular time from a specific sensor, which, in turn, would need to get correlated with vehicle, stop, and trip level information in order to produce reports such as bus crowding levels during peak hours so schedules can be modified to promote safety for riders.

To fill in the gaps that exist, larger agencies with IT teams are often devising one-off solutions to meet their unique needs. However, these are often not shared more broadly, in part because so much is custom to their specific technology that’s been deployed. As a result, smaller agencies that do have technology often have data that they could theoretically leverage to improve service, but are unable to do so because of technical barriers.

Additionally, transparent sharing of data is not common practice and while some agencies may share reports (Example from SFMTA, San Francisco Municipal Transportation Agency: https://www.sfmta.com/performance-metrics), they are often at aggregate levels which make it hard for transit advocates and academic researchers to leverage, such as to understand opportunities for faster public transportation through dedicated bus lanes or transit signal priority (TSP). One example of an agency making information available at a highly granular level is the Massachusetts Bay Transportation Authority (MBTA), through their [MBTA-Performance API](https://www.mbta.com/developers/mbta-performance).

## Proposed Solution

[This proposal](http://bit.ly/gtfs-performance) offers an extension to the static GTFS file, like [GTFS-ride](https://github.com/ODOT-PTS/GTFS-ride/blob/master/spec/en/reference.md), to support the transmission of historical transit performance data and also borrows fields from the proposed [GTFS-ServiceChange V3.1 specification](http://bit.ly/gtfs-service-changes-v3_1) to account for ad-hoc changes to service as operations teams respond and address operational challenges. These additional files specified here will reference files already defined in the GTFS, such as stops.txt through foreign keys like stop_id.

The most granular level of data can be made available through stop_observations.txt, which will provide stop-level information such as estimated arrival/departure times and recorded boardings/alightings.

Additionally, aggregates of the data can be made available, such as stop-to-stop travel times through travel_dwell_times.txt, and KPIs through performance_stats.txt.

This proposal is intended to align with the highly related effort from TCRP G-18 to define a broad set of data standards for historical data. For more details, see [TCRP G-18: Draft Data Structure & Tool Requirements SHARE](https://docs.google.com/document/d/1nI6mWLeFXDpAEQ_FxJEYHHBR28dmYS1L_tpGjxJQoxE/edit?usp=sharing).  

## Feedback & Next Steps
We'd love to hear any reactions and feedback from the broader community in terms of your needs! Feel free to leave your comments directly on [the proposal](http://bit.ly/gtfs-performance).

### For Data Producers
- If your software produces this type of information, how do your users get this information today? Are there any existing data formats the GTFS community should also be aware of?
- Is this type of specification feasible? If not, what other representations might make sense?
- What other pieces of data might this standard want to support? 
- Are there additional interfaces needed between transit hardware and software vendors to exchange a partial view of historical data to facilitate building out a more complete picture?  

### For Agencies & Data Consumers
- How do you get this type of information today, if at all, from existing systems? What current pain points or problems do you have?
- In what types of applications might this data be leveraged? Is there interest in publishing this information publicly on open data portal?
- Is a ZIP file, like GTFS and GTFS-ride, with this data the right format? If not, what other formats or mechanisms (such as a standardized API) might be more appropriate?

Thanks for your thoughts and looking forward to the discussion! For more information, please see [bit.ly/gtfs-performance](http://bit.ly/gtfs-performance).

**Comment by stevenmwhite** [comment]
Have you been in touch with the folks at Cal-ITP? They're currently working (with a working group) on a proposal for an Operational Data Standard extension to GTFS. This standard is meant to include operational plan information about drivers and vehicles, but also realized information such as on time performance. Perhaps it is best to work through that working group, which I believe intends to wrap up with a proposal around the end of the year.

**Comment by Cristhian-HA** [comment]
@mcplanner @e-lo this might interest you

**Comment by ericouyang** [comment]
Thanks for flagging the Cal-ITP folks! Yes, I'm in touch with @safrazier17 and familiar with the exciting effort he's leading at Cal-ITP on the [Operational Data Standard](https://docs.calitp.org/operational-data-standard/).

My understanding is that the nearer-term focus of that effort is more around representing additional scheduled events outside of revenue service, like the expected timing of pull in/outs. Definitely looking forward to collaborating with that group and figuring out how this all might fit together!

**Comment by skinkie** [comment]
What I am missing in your problem definition is the quality of the 
predictions. With every prediction a quality indicator could theoretically 
be given how well that prediction was, instead you only focus on passing 
times. Hence if you want to define an exchange of *executed data*, I would 
suggest just use GTFS as denormalised delivery without the fancy pancy 
things you have added. Sure somethings are not available at that time such 
as frequencies and calendar.txt, but in general a stop_times.txt + 
calendar_dates.txt is likely describing everything you want in concert with 
the GTFS publication valid on that date. Now we could start a discussion on 
service modifications that could introduce new trips, which justifies 
building a new timetable... (down the rabbit hole)

If you describe a data model, then just define the transformations on how 
the most granular data can be transformed into that and/or write the code 
for that effort.

--
Stefan

**Comment by ericouyang** [comment]
Hi @skinkie  - In the specification proposal, you'll note that it does represent service modifications, including new trips (schedule_relationship=DUPLICATED) in GTFS-realtime TripUpdates. You're right that one could theoretically capture actual historical observations within stop_times.txt (though we would need to somehow also account for frequency-based service). However, then, there would still need to be some extension to GTFS to represent whether or not stop_times.txt is scheduled times or observed times to avoid potential confusion. Moreover, agencies often need to compare actual service vs. scheduled service. Do you have a suggestion in terms of how that could work in that paradigm?

My personal opinion on the matter is that it's better to be an explicitly different file to avoid potential ambiguity.

I agree that there's a potential standard that could be developed around the accuracy of predictions, but that's not the focus here. I think the best way to do prediction accuracy comparison is to basically store in a flattened file the values of StopTimeUpdate from GTFS-realtime, which is what I believe some of [the archival tools referenced within awesome-transit](https://github.com/CUTR-at-USF/awesome-transit#gtfs-realtime-and-other-real-time-api-archival-tools) do. With a recording of predictions, they can then be compared to the actual observations from stop_observations.txt defined here.

**Comment by skinkie** [comment]
> Moreover, agencies often need to compare actual service vs. scheduled service. Do you have a suggestion in terms of how that could work in that paradigm?

Change the filename, keep the same syntax. With respect to frequency based trips, that is the trivial one. For the duplicated trips, you may want to introduce a reinforcement number. But one could also argue, just introduce a new trip, with a suffixed trip-id, it it really important to know that it was a reinforcement of a specific template, or that the trip actually ran.

**Comment by drewda** [comment]
In case it's of interest to people finding this issue in the future, Interline and MTC are now producing a subset of `stop_observations.txt` for the San Francisco Bay Area. More information at https://www.interline.io/blog/mtc-regional-stop-observations/

Thanks to the creators of this proposal!
