### ISSUE TITLE
Use of route type entity selector in GTFS RT alerts

### ISSUE THREAD

**Issue by optionsome** [google/transit#296]
From what I have witnessed, both the basic and the extended route types are being used for the route_type selector in alerts. If a data producer uses `route_type: 2` or `route_type: 100` as an entity selector, should it be interpreted that only the routes, which have one of those route_types in the static GTFS data, should be affected by the alert or also all 1xx route_type routes?

As it is also possible to define vehicle_type for stops.txt according to https://developers.google.com/transit/gtfs/reference/gtfs-extensions, should an alert that has a `route_type: 100` entity selector be interpreted to also affect all stops that have `route_type: 100` vehicle_type or should route_type entity selector be interpreted to only affect routes?

**Comment by stevenmwhite** [comment]
My interpretation is that alerts using route type are expected to affect all routes of that type. This would be used, for example, who share an alert that affects the entire rail system at an agency that has both bus and rail routes.

**Comment by optionsome** [comment]
I can see that there could also be use in targeting an alert to a more limited set of routes through the extended route types, such as 705 - Night Bus Service. I often see that the data producers use the extended route types for routes that clearly differ from other routes. For the "regular" routes they might use the normal route types. Therefore, my intuition is that we should only link the alerts to the routes that have exactly the same route_type as in the alert entity. If a data producer wants an alert to be attached to all bus routes, for example, they should have entity selectors for each of the used bus route_types. However, my view on this is limited to the data sets that I use and I don't have knowledge on how different systems interpret these entities currently nor how the data producers, in general, use them.

**Comment by BodoMinea** [comment]
My interpretation is also for exact matching. A route_type alert should only apply to routes and those being of that exact type. The extension to stops.txt that you're bringing into this discussion is only used for using appropriate icon for the stop if I am not mistaken, and anyway, if you produce an alert for route_type TRAM, it will be shown by consumer apps „attached” to the trams that would pass through a stop having route_type tram, so interpreting it for stops too would be redundant in my opinion.
