### ISSUE TITLE
is_symmetrical in fare_leg_rules.txt and fare_transfer_rules.txt

### ISSUE THREAD

**Issue by omar-kabbani** [google/transit#305]
# is_symmetrical in fare_leg_rules.txt and fare_transfer_rules.txt

This GitHub issue was raised in response to a discussion in [pull Request #286](https://github.com/google/transit/pull/286), and has been prioritized by MobilityData, who is going to work on it with the agenda described below.

## The need
The specification should forbid:
 - Erroneous logical errors
 - Ambiguities regarding Primary Keys

## The issue
Currently, two entries in `fare_leg_rules.txt` and in `fare_transfer_rules.txt` can be identical except for values in the `is_symmetrical` field. This leads to conflicting information on whether the fare is symmetrical or not, see sample data below (are transfers from `area_2` to `area_1` possible or not)

|leg_group_id|from_area_id|to_area_id|network_id|is_symmetrical|
|--|--|--|--|--|
|group_1|area_1|area_2|bus|0|
|group_1|area_1|area_2|bus|1|
 
More importantly, this affects Primary Keys as the above sample data demonstrates that the other remaining four (or even six, if all fields are utilized) fields cannot describe a unique entry. This would require including `is_symmetrical` in the list of Primary Keys 

## Potential options

- Option 0: Leave as-is
	- Pros: Keeps the verbosity of the specification minimal 
	- Cons: Leaves the door open for logical errors, unnecessarily complicates Primary Keys
- Option 1: Extend the definitions of is_symmetrical with the following 
	- `fare_leg_rules.txt`: A record must not be duplicated with any arrangements of the same `from_area_id` and `to_area_id` values with different values for `is_symmetrical`.
	- `fare_transfer_rules.txt`: A record must not be duplicated with any arrangements of the same `from_fare_leg_id` and `to_fare_leg_id` values with different values for `is_symmetrical`.
		- Pros: Forbids ambiguous data and simplifies Primary Keys
		- Cons: Makes the specification more verbose, might set a precedence for adding more restrictions in the specification 

## MobilityData's recommendations
MobilityData recommends Option 1 as it addresses the needs raised in this issue.  

## Timeframes

2022-01-31: Issue opened on GitHub

### Phase 1
From 2022-01-31 to 2022-02-11 (10 business days): Conversations on GitHub with the community. 

### Phase 2
From 2022-02-14 to 2022-02-18 (5 business days): MobilityData will gather and analyze the feedback provided in phase 1, and will publish a summary by 2022-02-18.

### Phase 3
If the community is unable to reach consensus by the end of phase 1, MobilityData will call for three meetings to resolve any outstanding items regarding Primary Keys and `fare_leg_rules.is_symmetrical` and `fare_transfer_rules.is_symmetrical`. Feel free to block the below times in your calendars:
Meeting 1: 2022-02-22 13:00 to 14:00 ET
Meeting 2: 2022-02-23 13:00 to 14:00 ET
Meeting 3: 2022-02-24 13:00 to 14:00 ET
Please reach out to specifications@mobilitydata.org or react/reply to this message to receive a meeting invite. 

### Phase 4
From 2022-02-28 to 2022-03-04 (5 business days): MobilityData will gather and analyze the feedback provided in the phase 3, and will publish a summary by 2022-03-04.

### Phase 5
If consensus was reached, MobilityData will open the vote on the week of 2022-03-07, otherwise, MobilityData will act as a facilitator to help the community reach consensus through meetings, online conversations, or other appropriate means. The time period for this phase starts on 2022-03-07 and ends on 2022-03-11 (5 business days). MobilityData can be invited to take meetings notes or can be kept in Cc for those exchanges.

### Phase 6
From 2022-03-14 to 2022-03-19 (5 business days): MobilityData will gather and analyze the information shared during phase 5, and will publish a summary by 2022-03-19.

### Phase 7:
In all cases, the vote will be opened on the week of 2022-03-28. If the vote does not pass, MobilityData will end the work on these issues and will inform the community. This will not prevent other stakeholders from continuing the effort to drive the adoption of the base implementation of GTFS-Fares.

**Comment by jsteelz** [comment]
This proposal appears to be a logical consequence of https://github.com/google/transit/issues/304, and we suggest that the two discussions be merged.

**Comment by flocsy** [comment]
> Cons: Makes the specification more verbose, might set a precedence for adding more restrictions in the specification

Who said that is bad? We need the spec to be clear, precise, and leave as less as possible to interpretation, and shouldn't leave it intentionally vague as google did. (Especially if we already know the problems! Even if we'll think we thought about "every possible" problem and use case when we finalize the spec I'm 100% certain that we'll have some issues in the future that nobody thought about now.)

I think there are more problems that is not mentioned in the proposal.

leg_group_id | from_area_id | to_area_id | network_id | is_symmetrical
group_1 | area_1 | area_2 | bus | 1
group_1 | area_2 | area_1 | bus | 1

This is not controversial but the 2 lines basically mean the same and I'd rather forbid this unnecessary verboseness.

Also the proposed Option 1: would allow this (because is_symmetrical in the 2 rows is the same value):
group_1 | area_1 | area_2 | bus | 1
group_1 | area_2 | area_1 | bus | 1
and also this:
group_1 | area_1 | area_2 | bus | 0
group_1 | area_2 | area_1 | bus | 0
Note that the above 1st+2nd row are identical semantically to 3rd+4th row.

I think the constrains in the spec should only allow either one of the following rows:
group_1 | area_1 | area_2 | bus | 1
or
group_1 | area_2 | area_1 | bus | 1
Both of these rows alone are identical to 1st+2nd and also to 3rd+4th above.

I think is_symmetrical in not one of the "input" fields, and thus it should not be included in the primary key (see also: https://github.com/google/transit/issues/304#issuecomment-1028199279), but that alone is not enough as demonstrated. We do need the constraints in the spec.

**Comment by flocsy** [comment]
@jsteelz I agree the 2 are connected, but I think it's better to get to an agreement here first, and then it would already render a decision about is_symmetrical that could be carried over to #304

**Comment by npaun** [comment]
[I work with @jsteelz on Transit's Fares implementation]

I agree that the proposed wording leaves room for invalid records. My personal preference would be to not support `is_symmetrical` at all, but if we're going to have it, then maybe the following definition would be unambigious?

A record where `is_symmetrical=1` is invalid if it would violate any constraints were it written as two records with `is_symmetrical=0`. For example, a record `from_area_id=A, to_area_id=B, is_symmetrical=1` is equivalent to `from_area_id=A, to_area_id=B, is_symmetrical=0`; `from_area_id=B, to_area_id=A, is_symmetrical=0`.

**Comment by flocsy** [comment]
This would still leave the unnecessary verboseness allowed. Besides it's not clear what are the constraints that the sentence is referring to.
from_area_id=A, to_area_id=B, is_symmetrical=1, amount=1
from_area_id=B, to_area_id=A, is_symmetrical=1, amount=2
Is this allowed or not?

I think is_symmetrical should not be part of the key, that would already forbid this:
from_area_id=A, to_area_id=B, is_symmetrical=1, amount=1
from_area_id=A, to_area_id=B, is_symmetrical=0, amount=2

But we still need to include some sentence that forbids things like:
from_area_id=A, to_area_id=B, is_symmetrical=1, amount=1
from_area_id=B, to_area_id=A, is_symmetrical=0, amount=2
Maybe the following "trick" can help: if is_symmetrical=1 then from_area_id has to be <= to_area_id

**Comment by npaun** [comment]
I wonder if we should just delete the column is_symmetrical. I feel like the benefit it gives is less then all the verbiage we need to enforce that it is used correctly.

**Comment by omar-kabbani** [comment]
@flocsy can you please elaborate what you mean by this?

> Maybe the following "trick" can help: if is_symmetrical=1 then from_area_id has to be <= to_area_id

**Comment by omar-kabbani** [comment]
> I wonder if we should just delete the column is_symmetrical. I feel like the benefit it gives is less then all the verbiage we need to enforce that it is used correctly.

I think it would be helpful to hear what data producers think about this (Cal-ITP/MTC/Interline+others) - @e-lo @jewel1965 @drewda
If you or someone from your team can chime in it would be awesome!

**Comment by flocsy** [comment]
@omar-kabbani 
> @flocsy can you please elaborate what you mean by this?
> 
> > Maybe the following "trick" can help: if is_symmetrical=1 then from_area_id has to be <= to_area_id

I think it's very simple: if we require the area_id-s (from_area_id, to_area_id) to be listed in lexicographic order (in case they are numbers it's easy, but also not a big deal if they are strings) in case is_symmetrical = 1, it removes the problems caused by listing both: A, B, 1 and B, A, 1, and thus removes some of the problems.

**Comment by flocsy** [comment]
> I wonder if we should just delete the column is_symmetrical. I feel like the benefit it gives is less then all the verbiage we need to enforce that it is used correctly.

I tend to agree, though I am not afraid of verbosity of the spec, if it makes it a better spec. I am more concerned about the verbosity of the produced files, and adding is_symmetrical would make it possible to have 1/2 of the lines removed in most cases.

**Comment by omar-kabbani** [comment]
If I can also add that if we are unable to agree on `is_symmetrical`, we can exclude it for now, and then revisit including it in future pull requests if there is strong demand for it. This will allow us to move forward with getting the base implementation of GTFS-Fares v2 adopted. 
It is easier to introduce `is_symmetrical` down the road vs. adopting it now and then realizing there are problems with it + potentially removing it (breaking change).

**Comment by omar-kabbani** [comment]
Hi everyone, after a meeting with @flocsy, @jsteelz, @npaun, @philip-cline, @skinkie, and @Cristhian-HA today, it was decided to remove `fare_leg_rules.is_symmetrical` and `fare_transfer_rules.is_symmetrical` from the base implementation. This is because the fields can be used to create redundant or inconsistent records in GTFS datasets. 
The cons of enforcing proper use by adding restrictions on `is_symmetrical` outweigh the pros of having the fields in.
Removing `fare_leg_rules.is_symmetrical` and `fare_transfer_rules.is_symmetrical` will not reduce the functionalities in the base implementation of GTFS-Fares v2, the only downside is that it would require data producers to write two records instead of one when a rule applies both ways (A→B and B→A).
The fields can always be introduced in later pull requests when the need arises.
I am closing the issue and will soon update the files in the [pull request](https://github.com/google/transit/pull/286) to reflect this.
