### ISSUE TITLE
Discussion: pickup and drop-off fields in stop_times.txt

### ISSUE THREAD

**Issue by CharlesBelov** [google/transit#308]
The stop_times file has the following fields:

pickup_type | Enum | Optional | Indicates pickup method. Valid options are:
0 or empty - Regularly scheduled pickup. 
1 - No pickup available.
2 - Must phone agency to arrange pickup.
3 - Must coordinate with driver to arrange pickup.

drop_off_type | Enum | Optional | Indicates drop off method. Valid options are:
0 or empty - Regularly scheduled drop off.
1 - No drop off available.
2 - Must phone agency to arrange drop off.
3 - Must coordinate with driver to arrange drop off.

We have a situation where the drop-off type is "3 - Must coordinate with driver to arrange drop off". I believe we don't have a way to arrange for pick-up, but if a drop-off were to be requested by customer A and at that time customer B were to be waiting at the stop, I don't believe we would deny them boarding.

I'm leaning toward suggesting our agency use "1 - No pickup available", but that's likely not technically correct, even if it is the likely result in practice. It would be good to have a value "4 - Pickup only available in case of drop-off".

**Comment by stevenmwhite** [comment]
I'm mostly curious how a trip planner might use this new category.

I think you're right in that it's effectively a "no pickup available" because a trip planner won't have the ability to know if a passenger on board has requested a drop off from the driver, and this the trip planner would never want to suggest someone go wait at that stop _just in case_ the bus stops.

**Comment by CharlesBelov** [comment]
Agreed that from a trip planner perspective "no pickup available" is the best answer. What I don't want, though, is an driver mistakenly denying boarding to a random person at the stop when the stop is actually served because the data says "no pickup available" and they've seen that.

But yes, from a customer perspective, it is best that they not expect to be picked up there and not be waiting there, so I may be overthinking this.
