### ISSUE TITLE
chore: add issue templates

### ISSUE THREAD

**Issue by e-lo** [google/transit#311]
As a contributor/reviewer of GTFS, I'd like to understand what is expected for the following types of issues when submitting them, AND would appreciate a common structure when reviewing/commenting on them:  

 - Structural/major changes to GTFS (i.e. Fares v2) 
 - General suggested updates to the spec. 
 - Updates in descriptions/language which clarify the existing intent.

**Comment by lauramatson** [comment]
This would be very helpful! I might add a category for raising issues / gaps / questions that someone doesn't have a proposed solution for yet. Maybe that's encompassed by the second bullet point or maybe it's a precursor to it?

**Comment by e-lo** [comment]
This is being worked on here: https://github.com/MobilityData/transit/pull/64
