### ISSUE TITLE
How to change metro icon on google maps

### ISSUE THREAD

**Issue by federicof97** [google/transit#312]
Hi, I'm creating the feed for an italian agency. Italian metro icon on google maps are usually red, but when the agency published the gtfs feed, google creates blue M icon on each stop. How can I change this icon? Can I insert a different icon? thanks

**Comment by skinkie** [comment]
@federicof97 icons are not standardized yet. Contact your Google Transit support engineer for the available options.

**Comment by federicof97** [comment]
Thanks, so should I contact the google transit support and ask to change the icon? Because there isn't a txt file where I can specify the type of icon.

**Comment by federicof97** [comment]
> @federicof97 icons are not standardized yet. Contact your Google Transit support engineer for the available options.

Thanks, @skinkie  so should I contact the google transit support and ask to change the icon? Because there isn't a txt file where I can specify the type of icon.

**Comment by skinkie** [comment]
Exactly. And the icon file has been suggested here ;-)

https://github.com/google/transit/issues/312#issuecomment-1082834220

**Comment by federicof97** [comment]
@skinkie so I should add "route_icon_url" with the desidered icon in the routes.txt file? Thanks again

**Comment by skinkie** [comment]
> @skinkie so I should add "route_icon_url" with the desidered icon in the stops.txt file? Thanks again

No, this is a proposal and not implemented yet.

**Comment by federicof97** [comment]
@skinkie So I have to conctact the google support? I'm sorry, this is the first time for me with the gtfs files and google transit

**Comment by federicof97** [comment]
> > @skinkie So I have to conctact the google support? I'm sorry, this is the first time for me with the gtfs files and google transit
> 
> My first question is: do you even have access to partnerdash? If not, you should first become a partner for delivering this data.

Excuse me for not responding earlier. I logged on the partnerdash, I already uploaded the zip file with the gtfs static. Now should I contact the google partner for the custom icon? Thanks

**Comment by skinkie** [comment]
Likely the right step forward.

**Comment by emmambd** [comment]
It looks like this question was resolved, since there was a clear next step identified and the issue hasn't been followed up on in a year. As a result, I'm closing this issue. Thanks to @skinkie for providing support here!
