### ISSUE TITLE
translations.txt: `translation` should not be a primary key

### ISSUE THREAD

**Issue by jsteelz** [google/transit#323]
Currently, the primary key for `translations.txt` is `*`, meaning all fields are part of the primary key. However, this allows two identical records to be translated in different ways for one language, with no reasoning behind which translation should take precedence. It seems to me that this is in fact an error, and that the `translation` field should not be part of the primary key of the table.

Example:

```
table_name,field_name,language,translation,record_id,record_sub_id,field_value
routes,route_short_name,fr,métro,route_id_1,,
routes,route_short_name,fr,train,route_id_1,,
```

**Comment by timMillet** [comment]
PR https://github.com/google/transit/pull/326 replaces this issue
