### ISSUE TITLE
Splitting the field stop_times.end_pickup_dropoff_window

### ISSUE THREAD

**Issue by omar-kabbani** [google/transit#335]
This issue relates to the GTFS-Flex proposal, and is opened following a series of roundtable discussion to resolve the outstanding issues with the proposal. These discussions were hosted by MobilityData and attended by various stakeholders within the GTFS community.

You can find the GTFS-Flex proposal here: [https://github.com/MobilityData/gtfs-flex/blob/master/spec/reference.md](https://github.com/MobilityData/gtfs-flex/blob/master/spec/reference.md)  

-----------

The field `end_pickup_dropoff_window` should be split in two as service providers may have different rules regarding pickups and drop offs towards the end of service. 

End of service may either indicate:

- The last possible time for pickup
- The last possible time for riders to be dropped off

For that reason, we suggest replacing `end_pickup_dropoff_window` with:
- `last_pickup_time`:
    - Time after which pickups are no longer permitted for the on-demand service at a GeoJSON location, location group or stop. Pickups are permitted between `start_pickup_drop_off_window` and `end_pickup_window` inclusive. 
    - Conditionally Required:
        - Required if `stop_times.stop_id` refers to an ID from `location_groups.location_group_id` or ID from `locations.geojson` and if `last_drop_off_time` is empty.
        - Forbidden if `stop_times.arrival_time` or `stop_times.departure_time` are defined.
        - Optional otherwise. 

- `last_drop_off_time`: 
    - Time when the last drop off is permitted for the on-demand service at a GeoJSON location, location group or stop. Drop offs are permitted between `start_pickup_drop_off_window` and `end_drop_off_window` inclusive.
    - Conditionally Required:
        - Required if `stop_times.stop_id` refers to an ID from `location_groups.location_group_id` or ID from `locations.geojson` and if `last_pickup_time` is empty.
        - Forbidden if `stop_times.arrival_time` or `stop_times.departure_time` are defined.
        - Optional otherwise.

**Comment by westontrillium** [comment]
If we forbid intrazone travel within a single stop (#337), we do not need to split this field in two, and this can be solved a different way. With this forbid in place, usually, the `pickup_type=2` portion of the trip would only refer to pickup while the `drop-off_type=2` portion of the trip would only refer to drop-off. Example for intrazone travel:

trip_id | stop_id | stop_sequence | arrival_time | departure_time | pickup_type | drop_off_type | start_pickup_drop_off_time | last_pickup_drop_off_time
---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
trip1 | zoneA | 1 | | | 2 | 1 | 8:00 | 8:20 |
trip1 | zoneA | 2 | | | 1 | 2 | 8:00 | 8:45 |

If the service defines last pickup and drop-off times differently for a single zone with **no** intrazone travel, you can just split the record in two. Example:

trip_id | stop_id | stop_sequence | arrival_time | departure_time | pickup_type | drop_off_type | start_pickup_drop_off_time | last_pickup_drop_off_time
---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
trip1 | stopA | 1 | 8:00 | 8:00 | 0 | 0
trip1 | zoneA | 2 | | | 1 | 2 | 8:00 | 8:45 |
trip1 | zoneA | 3 | | | 2 | 1 | 8:00 | 8:20 |
trip1 | stopB | 4 | 8:50 | 8:50 | 0 | 0

**Comment by tsherlockcraig** [comment]
I agree with @westontrillium 's assessment that we don't need to do this if we repeat the service areas in stop times. I'm unsure if that is a point in favor of repeating service areas, or against.
- on the one hand, it means one less field
- on the other hand, it is yet another thing that a producer and consumer will need to be told about how the repeated service areas in stop_times works, that the second start_ and end_pickup_dropoff_time can be equal to or later than the end_pickup_dropoff_time (even though presumably the start_ value will vary much less often) and what it means when that is the case. This seems far less intuitive than the values 'end_pickup_time' and 'end_dropoff_time' which are relatively straight forward. (Although as discussed "intuitive" is subjective!)

**Comment by timMillet** [comment]
I'm slightly confused by the use of `last_pickup_time` and `last_drop_off_time` along with `end_pickup_window` and `end_drop_off_window` in each respective field definition.

Is `last_pickup_time` different from `end_pickup_window`? `last_drop_off_time` different from `end_drop_off_time`?
If not, I think using `end_pickup_window` and `end_drop_off_window` is better, as they end a time window started by `start_pickup_drop_off_window`.

**Comment by westontrillium** [comment]
@timMillet I *think* it's just a wording difference, not a functional one. Related issue on wording: https://github.com/google/transit/issues/336

**Comment by timMillet** [comment]
Thanks! I just wanted to be sure.
The last part of my remark comes from the roundtables [Omar mentioned](https://github.com/google/transit/issues/336#issue-1293508544). I think remembering "window" was preferred over "time" to emphasize it's not an exact time, but a time window.
No strong opinion on my side as long as the names are consistent.

**Comment by westontrillium** [comment]
Hmm, I had forgotten that line of reasoning!

If we kept the use of the word "window," then there would be no change to these fields needed (other than including the underscore in "drop_off"), since it would not make sense to say "first_pickup__drop_off_window/last_drop_off_window".

I'm fairly indifferent here as well, so I guess that means I would advocate the "least change" option. I'll add a comment to the other issue.

**Comment by omar-kabbani** [comment]
Got it - thanks everyone, I will close this issue and make the following change in the GTFS-Flex repository:
- Change the field name from `end_pickup_dropoff_window` to `end_pickup_drop_off_window`

**Comment by omar-kabbani** [comment]
I am closing this issue with https://github.com/MobilityData/gtfs-flex/commit/547200dfb580771265ae14b07d9bfd7b91c16ed2 incorporating the change discussed in this issue. 

The changes are now reflected in the [MobilityData/gtfs-flex repo](https://github.com/MobilityData/gtfs-flex/blob/master/spec/reference.md).
