### ISSUE TITLE
Changing start_pickup_dropoff_window to start_pickup_time

### ISSUE THREAD

**Issue by omar-kabbani** [google/transit#336]
This issue relates to the GTFS-Flex proposal, and is opened following a series of roundtable discussion to resolve the outstanding issues with the proposal. These discussions were hosted by MobilityData and attended by various stakeholders within the GTFS community.

You can find the GTFS-Flex proposal here: [https://github.com/MobilityData/gtfs-flex/blob/master/spec/reference.md](https://github.com/MobilityData/gtfs-flex/blob/master/spec/reference.md)  

-----------

To maintain consistency with the field names proposed in issue #335, we recommend renaming `start_pickup_dropoff_window` to `start_pickup_time`.

This also improves the spec logic since there is no need to define a time when drop offs are permitted - riders should be able to be dropped off anytime after pickup. For cases when zones only allow for drop offs but not pickups, the field `start_pickup_time` should be used used with a condition that forbids pickups in `pickup_type`.

**Comment by westontrillium** [comment]
We need to keep "drop-off" somewhere in the field name to account for drop-off-only windows.

I recommend: `start_pickup_drop_off_time`

**Comment by tsherlockcraig** [comment]
I agree with @westontrillium but also don't have a strong opinion. Would accept his alternative or the proposal.

I'm assuming following this proposal 'end_pickup_dropoff_window' would simply be changed to 'end_pickup_time'?

**Comment by leonardehrenfried** [comment]
I like @westontrillium's version.

**Comment by westontrillium** [comment]
Based on conversation [here](https://github.com/google/transit/issues/335#issuecomment-1226278468), I am amending my recommendation to retain the current wording, with the exception of adding the underscore between "drop_off" to stay consistent with GTFS. So the fields we would have to define the time range a rider can be picked up and/or dropped off would be:
- `start_pickup_drop_off_window`
- `end_pickup_drop_off_window`

**Comment by omar-kabbani** [comment]
Thanks everyone for the feedback, I will close this issue and make the following change in the GTFS-Flex repository:
- Change the field name from `start_pickup_dropoff_window` to `start_pickup_drop_off_window`

**Comment by omar-kabbani** [comment]
I am closing this issue with https://github.com/MobilityData/gtfs-flex/commit/547200dfb580771265ae14b07d9bfd7b91c16ed2 incorporating the change discussed in this issue. 

The changes are now reflected in the [MobilityData/gtfs-flex repo](https://github.com/MobilityData/gtfs-flex/blob/master/spec/reference.md).
