### ISSUE TITLE
Remove the "Conditionally Forbidden" presence condition from the spec 

### ISSUE THREAD

**Issue by isabelle-dr** [google/transit#347]
## Context
When a field is described as _Conditionally Required_ in the spec, three cases exist:

1. A field or file is **required under a certain condition, optional otherwise**. It is the case for the `calendar.txt`, `calendar_dates.txt`, and `levels.txt` files, for the fields `stops.stop_name`, `stops.stop_lat`, `stops.stop_lon`, `stops.zone_id` and for many other fields.

2. A field or file is **required under a certain condition, forbidden otherwise**. it is the case for `fare_transfer_rules.duration_limit_type`, `translations.record_id`, and `translations.field_value`.

3. A field or file is **required under a certain condition, forbidden under another condition, and optional otherwise**. It is the case for `stops.parent_station`.

## Problem
In the [Fares v2 base implementation PR](https://github.com/google/transit/pull/286), a new presence condition was added to the spec: **Conditionally Forbidden**, and was applied to `fare_transfer_rules.transfer_count`. This field has the behavior described in category 2 above: required under a certain condition, forbidden otherwise. 
We believe this field was initially designed as: _forbidden under a certain condition, optional otherwise_, and then changed when modifications were made to the PR.
This adds unnecessary complexity to the spec, this condition should only be used if a field is either forbidden or optional.

## Solution
Remove the _Conditionally Forbidden_ presence condition from the spec and describe `fare_transfer_rules.transfer_count` as _Conditionally Required_.

I'm happy to open a PR to do this fix if there is agreement from the community.

**Comment by emmambd** [comment]
👋 I'm going through our issue backlog to see if there's anything relevant to roll into the scope for #376. It looks like #376 may be a good opportunity to remove _Conditionally Forbidden_  as well since there was 4 thumbs up in favor of this issue and no dissent. 

Checking in with @isabelle-dr and those who +1'd: @westontrillium, @botanize, @timMillet, @jfabi

**Comment by isabelle-dr** [comment]
We can close - we can now make use of _Conditionally Forbidden_
