### ISSUE TITLE
Need clarification on routes.route_sort_order

### ISSUE THREAD

**Issue by mmorang** [google/transit#353]
Hello GTFS community.  I need some clarification regarding the route_sort_order field in routes.txt.

The current description of this field says "Orders the routes in a way which is ideal for presentation to customers. Routes with smaller route_sort_order values should be displayed first."

What does "displayed first" mean?  Let's say we have two routes with overlapping sections and route_sort_order 1 and 2.  I could interpret "displayed first" in two conflicting ways:
1) The route with route_sort_order 1 is drawn first in the map.  The route with route_sort_order 2 is drawn ON TOP of route_sort_order 1, thus covering it up.
2) The route with route_sort_order 1 is drawn on top in the map, covering up the route with route_sort_order 2.

Hoping someone can clarify the correct interpretation.

It would also be good to update the documentation to make this clearer.  For various bureaucratic reasons at my company, I'm unable to submit PRs myself in this repo, so it would be lovely if someone else could take care of it.

**Comment by westontrillium** [comment]
Trillium has interpreted `route_sort_order` as the way routes should be viewed in GTFS-powered vertical list displays (see screenshot).

<img width="974" alt="image" src="https://user-images.githubusercontent.com/57922264/195460623-01139870-e243-4d6d-a4fb-02a3468ef388.png">

**Comment by mmorang** [comment]
@westontrillium I'm not sure that clarifies anything for me regarding the map draw order.  Here it looks like the light blue line and green line draw on top of the yellow line, but I don't know what the sort order is for those colors.  I'm presuming the 10, 20, 30, etc. are not sort order numbers but route numbers.

Maybe route_sort_order is intended to be used only when listing routes and is not intended to convey map draw order at all.  Perhaps I've entirely misunderstood.

**Comment by westontrillium** [comment]
To clarify, yes, we interpret the field as *only* pertaining to list displays. It does raise an interesting question though, regarding whether it should refer to *any* hierarchical visualization, or if different kinds of visualizations need to be described with a different field(s).

The order of route layers on the example's map is unrelated to any rules explicitly set with `route_sort_order`. The list display implies the `route_sort_order` for 10: North County =`1`, 20: South County =`2`... 40: Southeast County =`4`, etc. "10," "20", etc. are bus route numbers.

**Comment by colemccarren** [comment]
I too have only ever interpreted this field as an indicator for the "correct" sorting of route_long_names or route_short_names, since either of these might be a mix of numbers or letters and not be easy to assume on an agency's behalf.

**Comment by LeoFrachet** [comment]
Hi Melina! Thanks for your question.

As author of the [`route_sort_order` proposal](https://github.com/google/transit/pull/83), I can share that I also intended that field to only have effect on the sorting of the routes in a list, and not on the ordering of the display of the transit shape layers on a map.

Does that answer your question?

**Comment by mmorang** [comment]
Yes, thank you for the conclusive response.  I ultimately decided not to try to use this field to control map drawing order since it didn't seem like it was intended for that, and now you have confirmed that this is the case.

I'll close this issue since my question has been answered.
