### ISSUE TITLE
fare_rules.txt requirement change in the Fares v2 base implementation is making existing data invalid

### ISSUE THREAD

**Issue by isabelle-dr** [google/transit#354]
👋 Hello GTFS Community! 
I'm opening this issue as a request for information from those who were involved in the Fares v2 discussions.

## Context
In PR #286, amending the specification with Fares v2 base implementation, **`fare_rules.txt` changed from being _Optional_ to being _Conditionally Required_ if `fare_attributes.txt` was present**. This change results in some existing production data becoming invalid, and I'd like to know if this was the intention.

Quoting @bdferris-v2 below, who is currently updating the [Canonical GTFS Schedule Validator](https://github.com/MobilityData/gtfs-validator) with the Fares v2 base implementation rules.
"Looking back at the original Fares V1 example documentation (not really hosted anywhere anymore, but available at https://web.archive.org/web/20111207224351/https://code.google.com/p/googletransitdatafeed/wiki/FareExamples), having a `fare_attributes.txt` file with a single entry and no `fare_rules.txt` file was a supported use-case for systems that have a single base fare.
There are 62 feeds in the [MobilityDatabase](https://database.mobilitydata.org/) that have a `fare_attributes.txt` file but no `fare_rules.txt` file. Of those, 39 have a single entry in `fare_attributes.txt`, indicating a default fare."

There was a [comment](https://github.com/google/transit/pull/286#issuecomment-1082480847) from @flocsy calling out this behavior, and I think during the roundtable discussions, it was decided not to tackle this problem to keep the focus on the scope of the PR (please correct me if I'm wrong).

## Needs
I would like to have insights from those who were involved in the Fares v2 base implementation so that MobilityData can best support the organizations that might be affected by this change.
- Is the behavior described above now a spec violation?
- I know there were many iterations in this PR. Was this change intentional, or was it part of an earlier version?

Thank you in advance 🙏

**Comment by flocsy** [comment]
You are right. I think some people freaked out of the 30+ points I raised and I was asked to indicate which issues I considered blocking and this wasn't one of them.

So as I also argued back then, I am in favor or remoivng this change and keep it Optional.

**Comment by isabelle-dr** [comment]
Okay, after some digging ⛏, here seems to be the order of events:

- The [initial commit](https://github.com/google/transit/pull/286/commits/2359064fc042da6ad297611e86f325ccecad089c) added the new `fare_leg_rules.txt` where the intention seemed to be that it was forbidden to use both fares v1 and fares v2 design in the same dataset. 
  - More specifically: it defined `fare_leg_rules.txt` and `fare_attributes.txt` as **Conditionally Forbidden** if the new `fare_leg_rules` was defined, and `fare_leg_rules` was described as **Conditionally Forbidden** if one of the other two was defined.
- A commit called [allow v1 and v2 to coexist](https://github.com/google/transit/pull/286/commits/3f1f92453bf6200a2cace12f0d0561e359a5b641) made all of these files optional.
- There was a [discussion](https://github.com/google/transit/pull/286/commits/3f1f92453bf6200a2cace12f0d0561e359a5b641#r732301316) about how to describe the relationship between these three files while preserving the backward compatibility. I am quoting @gcamp below:
  - The transition will happen naturally and I don't think the spec should dictate the best way to do it. [...] Producers will not drop fares v1 data until a good amount of consumers will support it.
- A last commit called [Patch presence requirements for v1](https://github.com/google/transit/pull/286/commits/4950fc73ade0f3981b8ba071685b9de8fa3212da) made `fare_rules.txt` Conditionally Required, and I believe there were no changes after.

**Comment by isabelle-dr** [comment]
It looks like the intention was **not** to make the behavior described above invalid, but to simply add clarification on the relationship of `fare_leg_rules.txt`, `fare_attributes.txt`, and `fare_attributes.txt`.

**Comment by flocsy** [comment]
I agree
