### ISSUE TITLE
Thoughts on forbidding "subfolder inside zip"?

### ISSUE THREAD

**Issue by thbar** [google/transit#377]
Hello,

While doing a pass of data quality on https://transport.data.gouv.fr, I noticed a dozen of GTFS zip files do not store the content at the top-level of the zip, but instead inside an arbitrarily-named subfolder. 

While some GTFS-reading tools appear to handle that just fine, it can be an extra hurdle for people integrating the data.

Wouldn't it be good to explicitly forbid this in the specification or in the guidelines?

Apologies if this topic has already been covered, I couldn't find a reference to that.

Thanks!

**Comment by leonardehrenfried** [comment]
We get lots of support requests for exactly this topic in the OpenTripPlanner chat room.

I would welcome the spec being more clear on this.

**Comment by evantrillium** [comment]
I upvote this - many GTFS producers incorrectly assume that simply having a zipped file is sufficient, and will often enclose them using software that malforms the enclosure.

**Comment by laurentg** [comment]
Mecatran: +1
Not forbidding this also raise the interesting question of what to do with multiple data inside multiple folders, or split in several folders. Forcing files to be at the root would be more convenient. The spec should at least strongly advise to do that.

**Comment by thbar** [comment]
In #379 I propose a PR (unsure what the recommended process is, at least this helped me figure out what a good place to state this would be).

**Comment by thbar** [comment]
I have opened the votes officially, please ensure your vote is listed in https://github.com/google/transit/pull/379#issuecomment-1620389980 ! (@leonardehrenfried @evantrillium @laurentg in particular, since you had already "voted" here). Thanks!

**Comment by thbar** [comment]
Thanks everyone for the feedback :-)
