### ISSUE TITLE
Add rule_priority field to fare_leg_rules.txt

### ISSUE THREAD

**Issue by tzujenchanmbd** [google/transit#383]
### Context
EDIT 2023-11-28: You can find the spec modeling proposal here [https://share.mobilitydata.org/rule-priority](https://share.mobilitydata.org/rule-priority).

The `rule_priority` field is derived from [Ito World's "override" proposal](https://docs.google.com/document/d/1Q7mo2k4j1-uEmaLYIQVoNqdR2a_xMj9Kc-iA9mGwnXo/edit#heading=h.4bej6s69xndk). In the past discussions there seems to be a consensus on renaming it to rule_priority while keeping the same semantics ([PR#357](https://github.com/google/transit/pull/357#issuecomment-1521374672)). The `rule_priority` field "is used to simply represent cases when some matching rules need to take precedence over other matching rules." It is an experimental field in the current [fares v2 proposal](https://docs.google.com/document/d/19j-f-wZ5C_kYXmkLBye1g42U-kvfSVgYLkkG5oyBauY/edit#bookmark=id.4k2yvx7ji4v9).

### Examples
Assuming the fare from ZoneA to ZoneB is 3.00, while there is an exception that from Airport Station within ZoneA to Central Station within ZoneB is 2.00. A straightforward approach would be defining **two** separate rules for ZoneA to ZoneB and Airport Station to Central Station. However, for a leg from Airport Station to Central Station, both rules would match, as Airport Station and Central Station belong to ZoneA and ZoneB respectively. (please see [Ito World's proposal](https://docs.google.com/document/d/1Q7mo2k4j1-uEmaLYIQVoNqdR2a_xMj9Kc-iA9mGwnXo/edit#) for more details)

Similar cases for time-variable fares: Assuming the peak hour is from 7:00 to 10:00 with a fare of 3.00, and the remaining hours are considered off-peak with a fare of 2.00. A simple approach could be like:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-e2b90748-7fff-24cd-3f0a-e07cb080896f"><div dir="ltr" style="margin-left:-41.25pt;" align="left">

timeframe_group_id | start_time | end_time | service_id
-- | -- | -- | --
peak | 7:00:00 | 10:00:00 | everyday

</div></b>
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9be7a645-7fff-6364-d20c-9b04688fe450"><div dir="ltr" style="margin-left:-21pt;" align="left">

leg_group_id | fare_product | from_timeframe_group_id | to_timeframe_group_id
-- | -- | -- | --
1 | peak | peak |  
1 | offpeak |   |  

</div></b>
However, for a leg starting at 7:30, both rules would match.

`rule_priority` indicates the priority among multiple matching rules, thereby providing accurate fares to riders. 
Adding `rule_priority` to the time-variable fares example above:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-c7daf807-7fff-d2ea-8143-f56d63b66bec"><div dir="ltr" style="margin-left:-21pt;" align="left">

leg_group_id | fare_product | from_timeframe_group_id | to_timeframe_group_id | rule_priority
-- | -- | -- | -- | --
1 | peak | peak |   | 1
1 | offpeak |   |   |  

</div></b>
Now only peak fare would be selected for a leg starting at 7:30, since the peak one with highest priority "1".

### Alternative considered
For the time-variable fares cases, in addition to defining the peak hour timeframe, producers have to explicitly define all other times of the day as off-peak timeframes (0:00-7:00 & 10:00-24:00 for the example above), and define rules for both peak and off-peak timeframes. The similar approach for zone-based fares requires producers to provide additional entries in `fare_leg_rules.txt`, which in some cases can be a significant number of extra rules (see Ito's proposal for more details). This approach could be less intuitive and blurs the original intention of simplifying producers' data.

Please share any thoughts on `rule_priority` in this issue.

**Comment by npaun** [comment]
At Transit, we're we're in favour of the idea of rule priority in principle, as a way to make fare leg rules easier to write and understand. A big thank you to the folks from ITO World who've been working on advancing this.

There are so many unanswered questions we need to hammer down, hence why we asked for it to be in another PR. 

So far the following questions have come up internally:

1. What happens when multiple matching `fare_leg_rules` have equal `rule_priority`? There should be a clear statement in this case.
2. The proposed changes appear to consist solely of adding a `rule_priority` field. As a result, the confusing special case for empty values for fields like `from_area_id`, `to_area_id` and `network_id` continues to apply (where they match all values not otherwise specified).
     - If left as is, we worry this would limit the value of `rule_priority`.
     - Perhaps when `rule_priority` is set, empty values truly mean `empty`?
     - Or instead, the use of empty values could be banned when `rule_priority` is set?
3. This proposal doesn't appear to be backwards compatible, in that consumers that do not recognize the `rule_priority` column will derive a different meaning for the fare leg rules than that intended by the producer. Users could see incorrect fare calculators.
     - I think the proposed specification text will need a clear and extensive section describing the backwards compatibility situation when `rule_priority` is used.
     - I've only skimmed the proposal so far; if it is in fact backwards compatible, I'd love to see a worked example.

**Comment by halbertram** [comment]
@npaun Glad it's looking useful.

Some initial answers:

1. I've tweaked the proposal mentioned to say "those rules" rather than "the one rule". Ie all rules that have the equal highest priority are selected and the rest discarded.
2. We have only used this in a world where those fields are never left empty (`from_area_id` = "anywhere" etc). I think working with them being empty would work, but maybe the the third option of requiring those fields be populated might be the best for now. At a later date, if we get a mechanism to opt-in change the rules of those empty values, we could relax that rule.
3. Agree it wouldn't be, and you would get multiple rules matching likely leading to presenting the wrong results. Additionally it would likely fail the primary key requirements. However, we see this as similar to any proposal that adds predicates to the fare leg rules, such as timeframes.

**Comment by halbertram** [comment]
We have been thinking about unintended consequences of `rule_priority` and considering whether we need a way to restrict its effect.

As an example, take the example at the top, and imagine that those are contactless fares, and there is a different cash fare that is constant through the whole day.

| leg_group_id | fare_product | from_timeframe_group_id | to_timeframe_group_id | rule_priority |
| ----- | ----- | ----- | ----- | ----- | 
| 1 | contactless_peak | peak | | 1 |
| 1 | contactless_offpeak | | |
| 1 | cash_allday | | |

In this case, when off-peak, the contactless and cash products will match. However in peak times, only the contactless_peak product will match, as it matching causes any `rule_priority`=0 rules to be discarded. This is clearly undesirable, and could be a surprise if those rules are much further apart in the file.

One approach could be to have an optional scope that limits the override mechanism eg

 leg_group_id | fare_product | from_timeframe_group_id | to_timeframe_group_id | rule_priority | rule_priority_scope_id |
| ----- | ----- | ----- | ----- | ----- | ----- | 
| 1 | contactless_peak | peak | | 1 | contactless |
| 1 | contactless_offpeak | | | | contactless |
| 1 | cash_allday | | |

This would be one way, it could also be something like a `fare_products.fare_product_group_id` that connects the two contactless products. 

This example also raises the question of whether the `rule_priority` mechanism operates on just the predicates in the fare leg rules, or whether it considers whether the fare products themselves actually match (at eg fare media level).


Our initial work around this feature was connected to zonal schemes, and so the language in the original proposal was around "cheaper fares being selected", such that we wouldn't present zones 1-4 as an option for a zones 2-3 journey. We probably need to resolve that case via a different mechanism, so I've changed the area-based proposal to override regardless of it being cheaper or more expensive.

**Comment by isabelle-dr** [comment]
Hey everyone - just a reminder that MobilityData is hosting a GTFS-Fares v2 monthly meeting, and we will discuss this issue tomorrow at 11 AM EDT. To participate in the meeting, please subscribe via [this link](https://www.eventbrite.ca/e/specifications-discussions-gtfs-fares-v2-monthly-meetings-tickets-522966225057).

For a summary and more details, please check out the [meeting notes](https://docs.google.com/document/d/1d3g5bMXupdElCKrdv6rhFNN11mrQgEk-ibA7wdqVLTU/edit#).

**Comment by isabelle-dr** [comment]
Hello, here is a recap of what was said during the last working group meeting on this issue. More details are available in the meeting notes (linked in the comment above).

- Consensus on needing the rule priority mechanism and having an alternative to the empty semantics (which is what is proposed in the [Fare leg rule "Scope" support](https://github.com/google/transit/issues/399)).
- We now need to delve into the specifics of how this new mechanism will operate. (i. e. the rule_priority mechanism could be used as a trigger mechanism, an Enum somewhere else, etc). Your thoughts are welcome here!
- It’s worth noting that a dataset using the current empty semantics can be converted to a dataset without empty semantics.

**Comment by tzujenchanmbd** [comment]
Hello, here is a recap of consensus reached during the working group meeting on September 26th. More details are available in the [meeting notes](https://docs.google.com/document/d/1d3g5bMXupdElCKrdv6rhFNN11mrQgEk-ibA7wdqVLTU/edit#heading=h.m76tbqeze8z9).

- There was agreement on moving forward with Option 1 for switching empty semantics (field presence on rule_priority as a trigger)
- There might be a need to tackle discussions around multi-leg trips in a different format as it represents a complicated discussion. MobilityData will discuss internally and communicate a proposed approach to the group.

**Comment by tzujenchanmbd** [comment]
Hello, 

We'll be confirming the opening of the PR for `fare_leg_rules.rule_priority` in tomorrow's working group meeting. Feel free to join tomorrow's discussion (please subscribe via [this link](https://www.eventbrite.ca/e/specifications-discussions-gtfs-fares-v2-monthly-meetings-tickets-522966225057) if you haven't already). Regarding the details discussed previously, please refer to the [meeting notes](https://docs.google.com/document/d/1d3g5bMXupdElCKrdv6rhFNN11mrQgEk-ibA7wdqVLTU/edit#heading=h.m76tbqeze8z9) (mainly from August and September).
