### ISSUE TITLE
Add fare_media_type=1 to fare_media.txt

### ISSUE THREAD

**Issue by tzujenchanmbd** [google/transit#384]
**Context**

Currently the valid options of `fare_media_type` enum are: 0-None, 2-Physical transit card, 3-cEMV, 4-Mobile app. `fare_media_type=1` for physical paper ticket has not been adopted yet. Here is the description of `fare_media_type=1` in the [GTFS fares v2 proposal](https://docs.google.com/document/d/19j-f-wZ5C_kYXmkLBye1g42U-kvfSVgYLkkG5oyBauY/edit#heading=h.za3q5ta4cnyd):
> 1: Physical paper ticket that allows a passenger to take either a certain number of pre-purchased trips or unlimited trips within a fixed period of time.

In the previous “add fare media” pull request, `fare_media_type=1` was reserved primarily because no producers were providing data at the time. For previous discussions on `fare_media_type` please refer to [PR#355](https://github.com/google/transit/pull/355) and the [working group meeting note](https://docs.google.com/document/d/1d3g5bMXupdElCKrdv6rhFNN11mrQgEk-ibA7wdqVLTU/edit#heading=h.623abjei5cqb)

**Value for adding this to GTFS**
- Showing the price for fares that are purchased on a paper ticket
- Showing what needs to be used to validate the ride (the paper ticket)

**Updates**

We have learned that PVTA and MBTA could be potential producers for `fare_media_type=1` (@jfabi). We hope to adopt `fare_media_type=1` once we confirm at least one consumer.

Please share any thoughts on `fare_media_type=1` in this issue.

**Comment by npaun** [comment]
Transit is a consumer as of yesterday.

**Comment by isabelle-dr** [comment]
@npaun this is great news!
Just to clarify, are you consuming data from PVTA and/or MBTA and would use their media type 1 if they provided it?

**Comment by npaun** [comment]
We're working with PVTA on adopting this feature, and are consuming this data from them in our staging environment. We can accept this data in production from PVTA and MBTA if and when they choose to include it.

**Comment by jfabi** [comment]
The MBTA plans on implementing `fare_media_type=1` in our production feed over the next week. We will let this group know once it is live!

**Comment by lhynes607** [comment]
Whoops, I forgot to comment here: PVTA has had `type=1` in production since last Thursday.

**Comment by emmambd** [comment]
Amazing news @jfabi and @lhynes607! @npaun are you able to confirm it's now being consumed by Transit?

**Comment by jfabi** [comment]
> The MBTA plans on implementing `fare_media_type=1` in our production feed over the next week. We will let this group know once it is live!

This is now live in the MBTA's GTFS feed [as of the past week](https://github.com/mbta/gtfs-documentation/pull/38).

**Comment by npaun** [comment]
On behalf of Transit, I can confirm that the changes made by PVTA and MBTA are in production in our system.
