### ISSUE TITLE
[Community Outreach] GTFS amendment process pain points - Your insights count!

### ISSUE THREAD

**Issue by eliasmbd** [google/transit#401]
👋 On September 6th 2023, MobilityData will be hosting a [2-part workshop in Valencia, Spain on the amendment process in GTFS](https://mobilitydata.org/2023-mobilitydata-european-workshop/). We will ask participants to identify pain points within the formal process as highlighted in [changes.md](https://github.com/google/transit/blob/master/gtfs/CHANGES.md) as well as other informal processes that occur. We will then ask the participants to prioritize the pain points and to provide a solution for a single pain point of their choosing. 

🤔 Here are some of the topics that might come up: 

- Versioning
- Voting
- Implementation
- Testing
- Consumer / Producer proof during testing
- Official Platforms to publish - Should they be mentioned in the process?

📢 Our ask to the community members (you) that won't be able to attend would be to share with us some of their pain points that they would like to highlight for participants to solve. We will be doing something similar in October for the [NYC workshops](https://mobilitydata.org/2023-mobilitydata-north-american-workshop/) with the goal to open a PR/issue with the proposed solutions. 

ℹ️ A pain point can be a process or an item that is missing, too complex, incomplete, too vague, … 

🙏 Please provide your pain point using this template:

> Name:
> Organization:
> Producer or Consumer:
> Pain point description: 
> What element of changes.md would it affect: 

🗒️ We will be sharing the solutions of the workshops so that you can comment and be kept in the loop. No specification level decisions will be made during the workshops.

**Comment by eliasmbd** [comment]
Thank you for you pain point! I will make sure to share it with the participants. This is something that I have also been reflecting on as community manager. We have recently been publishing blogpost on [MobilityData's website](https://mobilitydata.org/news/) as an added layer of communication. I look forward to what the participants will come up with next week.

**Comment by westontrillium** [comment]
Name: Weston Shippy
Organization: Trillium/Optibus
Producer or Consumer: Producer
Pain point description: https://github.com/google/transit/issues/395
What element of changes.md would it affect: [This section](https://github.com/google/transit/blob/master/gtfs/CHANGES.md#specification-amendment-process) could be updated to include a few requirements around disclosing the author's affiliation(s).

**Comment by eliasmbd** [comment]
@westontrillium Thanks for sharing your painpoint. Unfortunately, the Valencia workshops were held last week, but we will be holding similar ones in [NYC on the 16-17th October,](https://mobilitydata.org/2023-mobilitydata-north-american-workshop/) we will make sure that this point come up there.

**Comment by mmorang** [comment]
Is there a summary somewhere of what conclusions were reached during the workshop?

**Comment by eliasmbd** [comment]
@mmorang We can provide some of the conclusions after our NYC workshop to aggregate the whole. Solutions were provided and we hope to revise them in NYC on 16 October.

**Comment by eliasmbd** [comment]
As we summarize the solutions in the coming weeks, we recommend you visit the following blogposts on the workshops: 

- [Valencia Workshop Day 1](https://mobilitydata.org/the-2023-mobilitydata-european-workshop-highlights-from-day-one/)
- [Valencia Workshop Day 2](https://mobilitydata.org/the-2023-mobilitydata-european-workshop-highlights-from-day-two/)

- [NYC Workshop Day 1](https://mobilitydata.org/the-2023-mobilitydata-north-american-workshop-highlights-from-day-one/)
- [NYC Workshop Day 2](https://mobilitydata.org/the-2023-mobilitydata-north-american-workshop-highlights-from-day-two/)

**Comment by eliasmbd** [comment]
Issue is closed, summary of problems and solutions proposed in the Workshops in #413
