### ISSUE TITLE
"Service date" vs. "service day"

### ISSUE THREAD

**Issue by antrim** [google/transit#43]
Current Spec refers to "service date". Trips occur on a particular "service date". The service date begins on a particular calendar date, and may continue to the next calendar date. (i.e. if there is transit service past midnight, trips may begin at 25:00:00, etc.).

It appears that "service day" is a more accepted term in transit, and this feels more intuitive to me.

Examples of the use of the term "service day":

* Sacramento Regional Transit ([glossary of terms](https://www.sacrt.com/transitglossary.stm)):

> Service Span — The span of hours over which service is operated, e.g., 6 a.m. to 10 p.m. or 24 hr (owl). Service span often varies by weekday, Saturday, or Sunday.
>
> Synonyms: Span of Service, Service Day

* King County Metro ([Regional Day Pass](http://metro.kingcounty.gov/fares/pdf/regional-day-pass-faq.pdf)):

> The pass covers unlimited rides for a "service day" starting at first use and expiring at 3 a.m. the next day. Each Regional Day Pass covers rides with a one-way adult fare up to $3.50 ($1.75 senior/disabled).

**Comment by barbeau** [comment]
Agreed, "service day" makes more sense to me in this context.

**Comment by abyrd** [comment]
I confirm, "service day" is widely used in the FOSS GTFS community, source code comments, etc.

**Comment by LeoFR** [comment]
+1

**Comment by antrim** [comment]
Closing. Spec changed in #45.
