### ISSUE TITLE
[DRT] After the adoption of GTFS-Flex, stops.txt should no longer be a required file.

### ISSUE THREAD

**Issue by tzujenchanmbd** [google/transit#452]
### Context

Before the adoption of GTFS-Flex in [PR#433](https://github.com/google/transit/pull/433), `stops.txt`was the sole file in GTFS defining the geographic locations (geometry: points) where riders board and alight. However, after its adoption, producers can define riders boarding and alighting geographic areas through `locations.geojson` (geometry: polygons) as well. In theory, an agency may exclusively offer zone-based demand-responsive services, in which case the feed may only contain `locations.geojson` without `stops.txt`.

### Proposed change

Therefore, we suggest changing the presence of `stops.txt` from `Required` to `Conditionally required` (required if `locations.geojson` doesn't exist). 

### GTFS validator behavior

Once the spec is modified, the GTFS validator can make corresponding adjustments, such as:
- Both `stops.txt` and `locations.geojson` exist - no error
- Either `stops.txt` or `locations.geojson` exists - no error
- Neither `stops.txt` nor `locations.geojson` exists - error (missing required file stops.txt)

Please share any thoughts you have here. We plan to open a PR soon.

**Comment by LeoFrachet** [comment]
I support taking a decision in short term on that, since a few of us are currently working on GTFS-Flex implementation.

I'm leaning toward making it optional, but if people have strong opinions against that, let us know.
