### ISSUE TITLE
Is rider_categories.txt still valid to use

### ISSUE THREAD

**Issue by mpaine-act** [google/transit#493]
### Ask a question

In reviewing gtfs.org, there is a discrepancy between different pages regarding the use of rider_categories.txt:

•	Found on https://gtfs.org/community/extensions/fares-v2/ under Adoption tacker
•	Not found on https://gtfs.org/documentation/schedule/reference/
•	No reference to rider_categories.txt on https://gtfs.org/documentation/schedule/change_history/revision_history/

Note that transitpartners.webapps.google.com supports it to some extent.

![transitpartners warning](https://github.com/user-attachments/assets/893093ab-13f8-406f-aef4-8b1fdd72e708)

Is this still part of the GTFS-Static specification?

**Comment by eliasmbd** [comment]
@mpaine-act Thank you for bringing this up. 
`rider_categories.txt`is not currently adopted into GTFS as you can see in the adoption tracker of the Fares v2 Extension page. This means that this field is currently being developed by the Fares v2 Working Group. Only tested and adopted fields make into the reference document as a feature of GTFS. 

cc: @tzujenchanmbd

**Comment by mpaine-act** [comment]
Thank you.  I'll contact our regional MTC 511.org team to determine why they already implemented this file if it isn't yet tested and adopted.
