### ISSUE TITLE
Should `agency_fare_url` require a transactional website?

### ISSUE THREAD

**Issue by gcamp** [google/transit#523]
### Describe the problem

Right now, the definition of `agency_fare_url` is 

`URL of a web page that allows a rider to purchase tickets or other fare instruments for that agency online.`

However, in practice it seems that very few if any url used in `agency_fare_url` allow purchase of tickets but instead just has information on the fares themselves with no way to purchase directly. 

### Current use

[Here's a list](https://github.com/user-attachments/files/18011832/urls_only.txt) of all the URLs in the feeds we support a Transit. I didn't find one URL linking to somewhere where you can purchase fares directly. Some link to external website that do, but it's just one of the ways to purchase listed. 

### Proposed solution

Change the description of `agency_fare_url` to `URL of a web page that allows a rider to learn about fares for that agency online.`

**Comment by skalexch** [comment]
I agree, can it include either though? The optimal case, then the in-practice case to still encourage the optimal option. Something like:
`agency_fare_url`: `URL of a web page that allows a rider to purchase tickets or other fare instruments for that agency online, or a web page that allows a rider to learn about fares for that agency online`.

**Comment by miklcct** [comment]
I agree with your description. Some fares can't be bought online such as cash fares, bank card fares, etc.

**Comment by westontrillium** [comment]
Agree with the change, but can we simplify the language?

`URL of a web page where a rider can purchase tickets or other fare instruments for that agency, or of a web page containing information about that agency's fares.`

**Comment by gcamp** [comment]
Thanks everyone for the comments! I agree with your proposal @westontrillium, I've put it in a PR here : https://github.com/google/transit/pull/524. 

Any further discussion can happen in the PR.
