### ISSUE TITLE
Space after field name in agency.txt on the Developer Site

### ISSUE THREAD

**Issue by robertbenjamin** [google/transit#56]
Not sure if you guys have control of the developer site, but [here](https://developers.google.com/transit/gtfs/examples/gtfs-feed#agencytxt) there seems to be a space after the first field name in the example for `agency.txt`:

```
agency_id, agency_name,agency_url,agency_timezone,agency_phone,agency_lang

Should be:
agency_id,agency_name,agency_url,agency_timezone,agency_phone,agency_lang
```

**Comment by RachM** [comment]
Thanks! The developer website has a few areas where the content is out of sync with GitHub. We're working on this, and I'll close this bug once it is resolved.

**Comment by eduherminio** [comment]
Already fixed in https://github.com/google/transit/pull/53.

**Comment by RachM** [comment]
Should be fixed now. The developers.google.com site is now synced with GitHub.

**Comment by barbeau** [comment]
Yay, thanks @RachM!
