### ISSUE TITLE
Transfers day of week/time availability

### ISSUE THREAD

**Issue by linusnorton** [google/transit#68]
I have been trying to find the best way to add connections via footpath that are only available at certain times of the day.

My use case is that there are some footpaths around London that are quicker at certain times of the day because a station or footpath is open.

My understanding is that footpaths should be added as transfers but it doesn't contain fields to add this information. I looked at using the frequencies but they need a route and there is no route type for Walking. 

What is the best practice in this scenario?

**Comment by barbeau** [comment]
Footpaths currently aren't officially supported in the GTFS spec, although there have been proposals to add this in the past:
* https://groups.google.com/forum/#!topic/gtfs-changes/Gk88QYQYgtw
* https://groups.google.com/forum/#!topic/gtfs-changes/JBAT5iFqAlY

...and I believe OpenTripPlanner has preliminary support for this.

Outside of GTFS, this information can live in OpenStreetMap via the `highway=footway` tag:
http://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway

IIRC you can define conditional restrictions for times for when a footpath is open:
http://wiki.openstreetmap.org/wiki/Conditional_restrictions

**Comment by linusnorton** [comment]
I see, I must have misunderstood the purpose of a transfer. 

Both of those proposals seem to have died off which is a shame. I guess the typical thing to do is to provide an additional file with the relevant information.
