### ISSUE TITLE
developers.google.com GTFS reference out of sync with changes made via this repo

### ISSUE THREAD

**Issue by mmorang** [google/transit#71]
I was just looking at the [developers.google.com GTFS reference site](https://developers.google.com/transit/gtfs/reference/) and noticed that it _still_ hasn't been updated to reflect changes made to the GTFS specification via the proposal/vote/accept process used in this repo.  For example, the first change we made using that process, adding location_type 2 to define a station entrance, still has not been added there.

Google, please update your site and keep it in sync!

**Comment by barbeau** [comment]
Related pull request where the sync issue is being discussed - https://github.com/google/transit/pull/28.

**Comment by RachM** [comment]
The developers.google.com GTFS site is now updated - apologies for how long this took.

**Comment by barbeau** [comment]
Thanks @RachM! :)

**Comment by mmorang** [comment]
Yay!
