### ISSUE TITLE
stop_code details: should reference to "uniquely" be removed?

### ISSUE THREAD

**Issue by thomastrillium** [google/transit#77]
Adding as issue rather than PR for now in case there are other producers or consumers who have already solved this problem a different way, that should be discussed prior to PR. 

From stops.stop_code details in spec

> The stop_code field contains short text or a number that uniquely identifies the stop for passengers.

Problem:
How does this reflect on use for stations? A customer providing a real-time app or SMS system a stop_code for a station with X bus bays likely wants to be returned arrival/departures for multiple routes, or might not want to remember a different stop_code depending on what route they want info for.

Easy answer for system that is consuming data is to have the same stop_code for multiple stop_ids in the station. However, this seems to violate spec.

Proposed solution: Remove the word "uniquely" from the spec details, in order to make it clear that this is allowed.

**Comment by giocorti** [comment]
The word "uniquely" has been removed from the `stop_code` description. The description now reads

> Short text or a number that identifies the location for riders.

**Comment by skinkie** [comment]
@giocorti that sounds correct. Because the same stop code (not stop_id) could be equal for multiple agencies or different regions.

**Comment by barbeau** [comment]
Closing this as fixed per @giocorti's comment above.
