### ISSUE TITLE
Clarification needed for GTFS/GTFS-realtime license

### ISSUE THREAD

**Issue by barbeau** [google/transit#89]
@RachM @ca9 Could Google provide clarification for the GTFS/GTFS-realtime specification license?

The bottom of https://developers.google.com/transit/gtfs/reference/ says:

>Except as otherwise noted, the content of this page is licensed under the Creative Commons Attribution 3.0 License, and code samples are licensed under the Apache 2.0 License.

But the [LICENSE.md](https://github.com/google/transit/blob/master/LICENSE) file at the root of this repository says it's Apache v2.0.

Does the LICENSE.md file in this repo count as "otherwise noted", meaning that the GTFS license is under Apache v2.0?

Asked by @mmorang in this post on the transit-developers list:
https://groups.google.com/forum/#!topic/transit-developers/kuhRnxAUR6A

**Comment by mmorang** [comment]
Thanks for opening this @barbeau.  Looking forward to some clarification, @RachM.

**Comment by antrim** [comment]
Earlier note says the Spec is licensed under Apache 2.0: https://github.com/google/transit/pull/17#issuecomment-171634406

**Comment by barbeau** [comment]
IMHO this is still an open issue, and is probably even more confusing now than ever for newcomers to the spec.

To my knowledge GTFS is licensed under Apache v2.0. This canonical repo has this license:
https://github.com/google/transit/blob/master/LICENSE

However, the words "GTFS is licensed under Apache v2.0" don't appear anywhere to my knowledge.

And, pages like this:
https://github.com/google/transit/tree/master/gtfs/spec/en

...have this text at the bottom:

>Except as otherwise noted, the content of this page is licensed under the Creative Commons Attribution 3.0 License.

Many newcomers confuse the Google website for GTFS as the canonical spec:
https://developers.google.com/transit

That website has subpages that have similar text in the footer (which I believe is the standard Google template) - for example, https://developers.google.com/transit/gtfs has:

>Except as otherwise noted, the content of this page is licensed under the Creative Commons Attribution 4.0 License, and code samples are licensed under the Apache 2.0 License. For details, see the Google Developers Site Policies. Java is a registered trademark of Oracle and/or its affiliates.

The Google GTFS homepage above now, however, also says:

>The contents of this document are from the GTFS site.

...which points to:
https://gtfs.org/

And when you click on "License" on gtfs.org, it says:

>Except as otherwise noted, the content of this page is licensed under the Creative Commons Attribution 3.0 License, and code samples are licensed under the Apache 2.0 License.

So it's not clear what's "otherwise noted" - my assumption is that the "otherwise noted" is the Apache v2.0 license attached to this repo, but you need to trace back to this repo to find it. And, to my knowledge neither the Google GTFS site or the gtfs.org site actually point back to this GitHub repo as the main source of truth for GTFS (unless you count the ["Change the spec" page](https://developers.google.com/transit/gtfs/guides/changes-overview), which says to open a pull request here for new proposals)

I'd really like to see the online GTFS documentation cleaned up. Things I think would help:
1. Take the Google GTFS documentation offline and point to/redirect to GTFS.org instead (or an equivalent canonical rendered version of the canonical GitHub repo)
2. Make it clear in plain text on the main canonical GitHub repo page and rendered version what the license is ("GTFS is licensed under Apache v2.0")
3. Make it clear in the rendered version that the canonical source of truth for GTFS is this GitHub repo (e.g., via an "Propose edits on GitHub" button somewhere)

**Comment by barbeau** [comment]
>However, the words "GTFS is licensed under Apache v2.0" don't appear anywhere to my knowledge.

One correction to the above I noticed today - the README for GTFS Realtime (but not GTFS) does have an explicit reference to Apache v2.0 in the text.

https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/README.md

...says:
>The specification was designed through a partnership of the initial Live Transit Updates partner agencies, a number of transit developers and Google. The specification is published under the Apache 2.0 License.

**Comment by scmcca** [comment]
@barbeau 
> my assumption is that the "otherwise noted" is the Apache v2.0 license attached to this repo

With the Apache v2.0 [license](https://github.com/google/transit/blob/master/LICENSE) file at the google/transit repo-level, this is also my interpretation.

> to my knowledge neither the Google GTFS site or the gtfs.org site actually point back to this GitHub repo as the main source of truth for GTFS

There is actually a brief mention of google/transit being the source of truth for the specification references over in the gtfs.org [README](https://github.com/MobilityData/gtfs.org#editing-site-content).

Also in the gtfs.org README in the [License](https://github.com/MobilityData/gtfs.org#license) section:
> Except as otherwise noted, the content of this repository is licensed under the [Creative Commons Attribution 3.0 License](https://creativecommons.org/licenses/by/3.0/), and code samples are licensed under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0).

Putting all this together, I think any mention of "except as otherwise noted" is to assign a license to gtfs.org (or another site like Google's developer pages), while also allowing the hosted content pulled from other repositories to maintain the license assigned to them at their source-of-truth.

Does that make sense?

**Comment by barbeau** [comment]
Not really 😅.

The more I look at this, the more I believe Google's language of:

>Except as otherwise noted, the content of this repository is licensed under the [Creative Commons Attribution 3.0 License](https://creativecommons.org/licenses/by/3.0/), and code samples are licensed under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0).

...is really just a boilerplate template that they apply to all their websites, and it got slapped onto the Google GTFS website without anyone thinking about what the actual GTFS *spec* license was.

For example, the [website for the Google Maps Android SDK](https://developers.google.com/maps/documentation/android-sdk/overview) says:

>Except as otherwise noted, the content of this page is licensed under the [Creative Commons Attribution 4.0 License](https://creativecommons.org/licenses/by/4.0/), and code samples are licensed under the [Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0)...

And that same language is being carried over to gtfs.org as well as a copy/paste.

Ultimately, to my knowledge Google is the copyright holder (via the CLA that everyone signs when they contribute via pull requests) so it's really up to them to make it crystal clear what the GTFS spec license is on GitHub, as that's the canonical reference. 

Then, everyone who mirrors that content, including the Google website, should reference the source, name the copyright holder, and repeat the same license (e.g., "The GTFS specification is licensed by Google under the Apache v2.0 license and the official documentation can be found here on GitHub"). If other licenses are being applied to other content on the site (e.g., if MobilityData or Google want to add their own commentary on particular fields), then the site should make it clear what license applies and specify the content (e.g., "The MobilityData Best Practices are licensed by MobilityData under the Creative Commons Attribution 4.0 License").
