### ISSUE TITLE
Allow multiple feed entity types in a single feed

### ISSUE THREAD

**Issue by egorich239** [google/transit#9]
It has been discussed several times in the mailing list [1][2] that the limitation on single feed entity type per feed is artificial and can be removed.

I propose to reflect this in the GTFS RT Specification: https://github.com/google/transit/pull/7

[1] https://groups.google.com/d/msg/gtfs-realtime/_HtNTGp5LxM/VvDLkV4wTnAJ
[2] https://groups.google.com/forum/#!topic/gtfs-realtime/VCKRVEWZbUE

**Comment by barbeau** [comment]
@egorich239 I believe this issue can now be closed, as https://github.com/google/transit/pull/7 has been merged?
