### ISSUE TITLE
 "Times must be eight digits in HH:MM:SS format"?

### ISSUE THREAD

**Issue by karkusviktor** [google/transit#90]
This sentence appears twice in the specification in the stop_times.txt section.
Isn't it supposed to be 8 characters? Or 6 digits?
As far as I know the colon is not a digit.

**Comment by barbeau** [comment]
@karkusviktor I think you're right, this is probably a typo and it should read:
>Times must be six digits separated by two colons in HH:MM:SS format

...or something similar.  From a quick read the GTFS spec doesn't specify a standard for time format, but looking at [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) it seems to define `:` as a separator, not a digit.

**Comment by giocorti** [comment]
I'm working on a PR that addresses this issue in addition to a number of other editorial changes. Should be ready for review soon.
