### ISSUE TITLE
Opening and closing of votes should be announced on GTFS Changes Google Group

### ISSUE THREAD

**Issue by barbeau** [google/transit#96]
First mentioned in https://github.com/google/transit/pull/31#issuecomment-412488601.

Right now the GTFS and GTFS-realtime change processes don't say you should announce opening/closing votes on the Google Group:
* https://github.com/google/transit/blob/master/gtfs/CHANGES.md
* https://github.com/google/transit/blob/master/gtfs-realtime/CHANGES.md

We should add a step saying the opening and closing of the vote itself should be announced on [GTFS Changes mailing list](https://groups.google.com/forum/#!forum/gtfs-changes), as it could be a long period of time between when a proposal is first opened to when it's voted on.

**Comment by abyrd** [comment]
+1

**Comment by barbeau** [comment]
Not stale

**Comment by scmcca** [comment]
Perhaps we can add a point under article 5 to read:
> Opening and closing of votes should be announced on the GTFS Changes mailing list.

Do we want to keep this as a suggestion (should) or requirement (must)?

**Comment by barbeau** [comment]
I think it should be a MUST, to align with announcing the proposal, which is a MUST.

**Comment by scmcca** [comment]
That makes sense, should we move this to a PR:

> Opening and closing of votes must be announced on the GTFS Changes mailing list.
